/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2024-05-07 07:58:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend.auth;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.apx.radiance.util.HibernateUtil;
import org.hibernate.SessionFactory;
import org.hibernate.Session;
import com.apx.radiance.entity.City;
import java.util.List;
import java.util.Iterator;

public final class sign_002din_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.apx.radiance.entity.City");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("com.apx.radiance.util.HibernateUtil");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("org.hibernate.Session");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Sign In | Sign Up</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/style.css\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/logos/logo short.svg\" type=\"image/x-icon\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-6 left-img-area d-none d-md-block position-fixed\"></div>\r\n");
      out.write("        <div class=\"col-6 d-none d-md-block\"></div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 col-md-6 col-lg-4 d-flex align-items-center\">\r\n");
      out.write("            <div class=\"row p-3 pt-5 mt-4 mt-xxl-5\" id=\"sign_in_area\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"logo\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mt-3\">\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"pagination-links\">Home</a>\r\n");
      out.write("\r\n");
      out.write("                    <span><i class=\"bi bi-chevron-right fs-mini fw-bold\"></i></span>\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("sign-in\" class=\"pagination-links active-page\">Sign In</a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mt-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <span class=\"main-heading\">Sign In</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6 text-end\">\r\n");
      out.write("                            <button class=\"nw-acc-btn\" onclick=\"register_form();\">Create New Account</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mt-4\">\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"fw-bold sm-text ms-2 d-block\">Username</span>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input id=\"loginUsername\" type=\"text\" class=\"form-control\" placeholder=\"Username\"\r\n");
      out.write("                               aria-describedby=\"button-addon2\">\r\n");
      out.write("                        <button class=\"btn-none\" type=\"button\"><i class=\"bi bi-person\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <span class=\"fw-bold sm-text ms-2 d-block mt-4\">Password</span>\r\n");
      out.write("                    <div class=\"input-group\">\r\n");
      out.write("                        <input id=\"loginPassword\" type=\"password\" class=\"form-control\" placeholder=\"Password\"\r\n");
      out.write("                               aria-describedby=\"button-addon2\">\r\n");
      out.write("                        <button class=\"btn-none\" type=\"button\"><i class=\"bi bi-key\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-6 mt-4\">\r\n");
      out.write("                    <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"flexCheckDefault\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("                            Remember Me\r\n");
      out.write("                        </label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-6 text-end mt-4 text-black-50\">\r\n");
      out.write("                    <span>Fogot Password ?</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mt-5 d-flex justify-content-center\">\r\n");
      out.write("                    <button onclick=\"signIn()\" class=\"sign-in-btn shadow\">Sign In <i\r\n");
      out.write("                            class=\"bi bi-chevron-right ms-3 position-absolute\"></i>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mt-4 text-center\">\r\n");
      out.write("                    <span class=\"sm-text text-black-50\">or</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 text-center\">\r\n");
      out.write("                    <span class=\"text-black-50\">Sign In With</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 d-flex justify-content-center mt-3\">\r\n");
      out.write("                    <button class=\"social-btn-sign-in\"><i class=\"bi bi-google\"></i></button>\r\n");
      out.write("                    <button class=\"social-btn-sign-in\"><i class=\"bi bi-facebook\"></i></button>\r\n");
      out.write("                    <button class=\"social-btn-sign-in\"><i class=\"bi bi-twitter\"></i></button>\r\n");
      out.write("                    <button class=\"social-btn-sign-in\"><i class=\"bi bi-apple\"></i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- <div class=\"col-12 d-flex justify-content-center mt-2\">\r\n");
      out.write("\r\n");
      out.write("                </div> -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row p-3 d-none\" id=\"sign_up_area\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"logo\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mt-3\">\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"pagination-links\">Home</a>\r\n");
      out.write("\r\n");
      out.write("                    <span><i class=\"bi bi-chevron-right fs-mini fw-bold\"></i></span>\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("sign-in\" class=\"pagination-links active-page\">Sign Up</a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mt-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-6\">\r\n");
      out.write("                            <span class=\"main-heading\">Sign Up</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-6 text-end\">\r\n");
      out.write("                            <button class=\"nw-acc-btn\" onclick=\"sign_in_form();\">Already have a account</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-6 mt-2\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label sm-text fw-bold ms-2\">First Name</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"first-name\" placeholder=\"Ex: John\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-6 mt-2\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label sm-text fw-bold ms-2\">Last Name</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"last-name\"\r\n");
      out.write("                               placeholder=\"Ex: Ferdinandis\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mt-2\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label sm-text fw-bold ms-2\">Email Address</label>\r\n");
      out.write("                        <input onkeyup=\"generateUsername();\" type=\"email\" class=\"form-control\" id=\"email\"\r\n");
      out.write("                               placeholder=\"Ex: hello@example.com\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-6 mt-2\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label sm-text fw-bold ms-2\">Mobile Number</label>\r\n");
      out.write("                        <input onclick=\"generateUsername();\" type=\"text\" class=\"form-control\" id=\"mobile\"\r\n");
      out.write("                               placeholder=\"Ex: 0701234567\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-6 mt-2\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label sm-text fw-bold ms-2\">Create\r\n");
      out.write("                            Username</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"username\" disabled placeholder=\"Ex: John@2001\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-6 mt-2\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label sm-text fw-bold ms-2\">Password</label>\r\n");
      out.write("                        <input onclick=\"generateUsername();\" type=\"password\" class=\"form-control\" id=\"password\"\r\n");
      out.write("                               placeholder=\"Include: Number, Uppercase Characters\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-6 mt-2\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label sm-text fw-bold ms-2\">Confirm\r\n");
      out.write("                            Password</label>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" id=\"confirm-password\"\r\n");
      out.write("                               placeholder=\"Include: Number, Uppercase Characters\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label sm-text fw-bold ms-2\">Address Line\r\n");
      out.write("                            01</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"address-line-01\" placeholder=\"Flower Road\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label sm-text fw-bold ms-2\">Address Line\r\n");
      out.write("                            02</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"address-line-02\" placeholder=\"Lake Area\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label sm-text fw-bold ms-2\">City</label>\r\n");
      out.write("                        <select name=\"\" id=\"city\" class=\"form-control mt-2\">\r\n");
      out.write("                            <option value=\"0\">Select City</option>\r\n");
      out.write("                            ");


                                SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
                                Session openSession = sessionFactory.openSession();

                                List<City> cities = openSession.createQuery("select city from City city", City.class).getResultList();

                                Iterator<City> iterator = cities.iterator();
                                while (iterator.hasNext()) {
                                    City cityData = iterator.next();

                            
      out.write("\r\n");
      out.write("                            <option value=\"");
      out.print(cityData.getId());
      out.write('"');
      out.write('>');
      out.print(cityData.getName());
      out.write("</option>\r\n");
      out.write("                            ");

                                }

                            
      out.write("\r\n");
      out.write("                        </select>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-6 mt-2\">\r\n");
      out.write("                    <div class=\"mb-3\">\r\n");
      out.write("                        <label class=\"form-label sm-text fw-bold ms-2\">Postal Code</label>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" id=\"postal-code\" placeholder=\"Ex: 600026\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mt-5 d-flex justify-content-center\">\r\n");
      out.write("                    <button class=\"sign-in-btn shadow\" onclick=\"signUp()\">Sign Up</button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    const BASE_URL = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script src=\"//code.tidio.co/obgngwi69oy3kootdyykcvyeujlvlgs1.js\" async></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/bootstrap.bundle.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/script.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
