/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2024-05-07 07:58:13 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.backend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/vidhu/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1702261288258L));
    _jspx_dependants.put("jar:file:/C:/Users/vidhu/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/backend/admin.jsp(3,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/backend/admin.jsp(5,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      // /WEB-INF/views/backend/admin.jsp(5,4) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setType("REPLACE");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.4.1.slim.min.js\"\r\n");
      out.write("                integrity=\"sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n\"\r\n");
      out.write("                crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css\" rel=\"stylesheet\">\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12 my-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-3 bg-white p-2 d-none d-lg-block\">\r\n");
      out.write("                                ");
      out.write("\r\n");
      out.write("                            <nav>\r\n");
      out.write("                                <div class=\"nav nav-tabs\" id=\"nav-tab\" role=\"tablist\">\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"\" class=\"nav-btn active w-100 text-start\"><i\r\n");
      out.write("                                            class=\"bi bi-grid-1x2-fill me-3 ms-1\"></i> Dashboard\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin/product\" class=\"nav-btn w-100 text-start\" id=\"nav-profile-tab\"><i\r\n");
      out.write("                                            class=\"bi bi-box-seam me-3 ms-1\"></i> Manage Products\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin/orders\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                            class=\"bi bi-cart me-3 ms-1\"></i> Orders\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin/users\" class=\"nav-btn w-100 text-start\" id=\"nav-contact-tab\">\r\n");
      out.write("                                        <i class=\"bi bi-people me-3 ms-1\"></i> Manage Users\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                            class=\"bi bi-bar-chart me-3 ms-1\"></i> Statictics\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                            class=\"bi bi-chat-left-text me-3 ms-1\"></i> Reviews\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                            class=\"bi bi-wallet2 me-3 ms-1\"></i> Transactions\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                            class=\"bi bi-box2-heart me-3 ms-1\"></i> Offers\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <hr>\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                            class=\"bi bi-person-circle me-3 ms-1\"></i> Account\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"\" class=\"nav-btn w-100 text-start\">\r\n");
      out.write("                                        <i class=\"bi bi-box-arrow-in-left me-3 ms-1\"></i> Log Out\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                            class=\"bi bi-brush me-3 ms-1\"></i> Appearance\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                    <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                            class=\"bi bi-gear me-3 ms-1\"></i> Settings\r\n");
      out.write("                                    </a>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </nav>\r\n");
      out.write("                                ");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-9\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"tab-content\" id=\"nav-tabContent\">\r\n");
      out.write("\r\n");
      out.write("                                ");
      out.write("\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-12 col-lg-10\">\r\n");
      out.write("                                        <div class=\"input-group mb-3\">\r\n");
      out.write("                                            <span class=\"input-group-text\" id=\"basic-addon1\"><i\r\n");
      out.write("                                                    class=\"bi bi-search\"></i></span>\r\n");
      out.write("                                            <input type=\"text\" class=\"form-control\" placeholder=\"Search....\"\r\n");
      out.write("                                                   aria-label=\"Username\" aria-describedby=\"basic-addon1\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-10 d-grid d-block d-lg-none\">\r\n");
      out.write("                                        <button class=\"btn-my w-100 text-start fw-bolder\" type=\"button\"\r\n");
      out.write("                                                data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasExamplead\"\r\n");
      out.write("                                                aria-controls=\"offcanvasExample\"><i class=\"bi bi-grid me-3\"></i> Menu\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"offcanvas offcanvas-start\" tabindex=\"-1\" id=\"offcanvasExamplead\"\r\n");
      out.write("                                         aria-labelledby=\"offcanvasExampleLabel\">\r\n");
      out.write("                                        <div class=\"offcanvas-header\">\r\n");
      out.write("                                            <h5 class=\"offcanvas-title\" id=\"offcanvasExampleLabel\">Menu</h5>\r\n");
      out.write("                                            <button type=\"button\" class=\"btn-close text-reset\"\r\n");
      out.write("                                                    data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                            ");
      out.write("\r\n");
      out.write("                                        <div class=\"offcanvas-body\">\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-12 bg-white p-2\">\r\n");
      out.write("\r\n");
      out.write("                                                    <nav>\r\n");
      out.write("                                                        <div class=\"nav nav-tabs\" id=\"nav-tab\" role=\"tablist\">\r\n");
      out.write("\r\n");
      out.write("                                                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin-panel\" class=\"nav-btn active w-100 text-start\"><i\r\n");
      out.write("                                                                    class=\"bi bi-grid-1x2-fill me-3 ms-1\"></i> Dashboard\r\n");
      out.write("                                                            </a>\r\n");
      out.write("\r\n");
      out.write("                                                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin/product\" class=\"nav-btn w-100 text-start\" id=\"nav-profile-tab\"><i\r\n");
      out.write("                                                                    class=\"bi bi-box-seam me-3 ms-1\"></i> Manage Products\r\n");
      out.write("                                                            </a>\r\n");
      out.write("\r\n");
      out.write("                                                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin/orders\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                                                    class=\"bi bi-cart me-3 ms-1\"></i> Orders\r\n");
      out.write("                                                            </a>\r\n");
      out.write("\r\n");
      out.write("                                                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin/users\" class=\"nav-btn w-100 text-start\" id=\"nav-contact-tab\">\r\n");
      out.write("                                                                <i class=\"bi bi-people me-3 ms-1\"></i> Manage Users\r\n");
      out.write("                                                            </a>\r\n");
      out.write("\r\n");
      out.write("                                                            <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                                                    class=\"bi bi-bar-chart me-3 ms-1\"></i> Statictics\r\n");
      out.write("                                                            </a>\r\n");
      out.write("\r\n");
      out.write("                                                            <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                                                    class=\"bi bi-chat-left-text me-3 ms-1\"></i> Reviews\r\n");
      out.write("                                                            </a>\r\n");
      out.write("\r\n");
      out.write("                                                            <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                                                    class=\"bi bi-wallet2 me-3 ms-1\"></i> Transactions\r\n");
      out.write("                                                            </a>\r\n");
      out.write("\r\n");
      out.write("                                                            <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                                                    class=\"bi bi-box2-heart me-3 ms-1\"></i> Offers\r\n");
      out.write("                                                            </a>\r\n");
      out.write("\r\n");
      out.write("                                                            <hr>\r\n");
      out.write("\r\n");
      out.write("                                                            <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                                                    class=\"bi bi-person-circle me-3 ms-1\"></i> Account\r\n");
      out.write("                                                            </a>\r\n");
      out.write("\r\n");
      out.write("                                                            <a href=\"\" class=\"nav-btn w-100 text-start\">\r\n");
      out.write("                                                                <i class=\"bi bi-box-arrow-in-left me-3 ms-1\"></i> Log Out\r\n");
      out.write("                                                            </a>\r\n");
      out.write("\r\n");
      out.write("                                                            <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                                                    class=\"bi bi-brush me-3 ms-1\"></i> Appearance\r\n");
      out.write("                                                            </a>\r\n");
      out.write("\r\n");
      out.write("                                                            <a href=\"\" class=\"nav-btn w-100 text-start\"><i\r\n");
      out.write("                                                                    class=\"bi bi-gear me-3 ms-1\"></i> Settings\r\n");
      out.write("                                                            </a>\r\n");
      out.write("\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </nav>\r\n");
      out.write("\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                            ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-1\">\r\n");
      out.write("                                        <button class=\"btn-my\"><i class=\"bi bi-bell\"></i></button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"col-1\">\r\n");
      out.write("                                        <button class=\"btn-my\"><i class=\"bi bi-gear\"></i></button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                                ");
      out.write("\r\n");
      out.write("                                <div class=\"p-2 tab-pane fade show active\" id=\"Dashboard\" role=\"tabpanel\"\r\n");
      out.write("                                     aria-labelledby=\"nav-home-tab\">\r\n");
      out.write("\r\n");
      out.write("                                    <span class=\"main-heading\">Dashboard</span>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-6 col-lg-4 p-2\">\r\n");
      out.write("                                            <div class=\"bg-white p-2 box-01\">\r\n");
      out.write("                                                <span class=\"main-heading text-black-50\">Daily Earnings</span>\r\n");
      out.write("                                                <span class=\"mt-3 d-block\">LKR.100,000.00</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-6 col-lg-4 p-2\">\r\n");
      out.write("                                            <div class=\"bg-white p-2 box-01\">\r\n");
      out.write("                                                <span class=\"main-heading text-black-50\">Total Orders</span>\r\n");
      out.write("                                                <span class=\"mt-3 d-block\">78465</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-6 col-lg-4 p-2\">\r\n");
      out.write("                                            <div class=\"bg-white p-2 box-01\">\r\n");
      out.write("                                                <span class=\"main-heading text-black-50\">Total Sales</span>\r\n");
      out.write("                                                <span class=\"mt-3 d-block\">LKR.1,550,700.00</span>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-12 col-lg-8 mt-2\">\r\n");
      out.write("                                            <span class=\"fw-bold\">Latest Orders</span>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"col-6 col-lg-12\">\r\n");
      out.write("                                                    <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                                                        <div class=\"col-12\">\r\n");
      out.write("                                                            <div class=\"row px-3 bg-white mt-2\">\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-1\">\r\n");
      out.write("                                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/products/ele 01.webp\"\r\n");
      out.write("                                                                         class=\"p-h-product-circle\" alt=\"\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-4 d-flex align-items-center\">\r\n");
      out.write("                                                                    <span class=\"text-truncate sm-text\">LED Recessed Spotlight 10W/12W/14W CCT Dimmable Spotlight Ceiling Spot 230V IP44 Round</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                                                                    <span class=\"text-black-50 fw-bold sm-text\"><i\r\n");
      out.write("                                                                            class=\"bi bi-clock-history\"></i> This Month</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                                                                    <span class=\"price-text fw-bold sm-text\">LKR. 11,250.00</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-1 d-flex align-items-center d-grid\">\r\n");
      out.write("                                                                    <button class=\"view-btn sm-text\">View</button>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"col-6 col-lg-12\">\r\n");
      out.write("                                                    <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                                                        <div class=\"col-12\">\r\n");
      out.write("                                                            <div class=\"row px-3 bg-white mt-2\">\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-1\">\r\n");
      out.write("                                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/products/hdmi port.jpg\"\r\n");
      out.write("                                                                         class=\"p-h-product-circle\" alt=\"\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-4 d-flex align-items-center\">\r\n");
      out.write("                                                                    <span class=\"text-truncate sm-text\">HDMI Male To VGA Male Video Converter Adapter Cable For PC DVD 1080P HDTV 6FT</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                                                                    <span class=\"text-black-50 fw-bold sm-text\"><i\r\n");
      out.write("                                                                            class=\"bi bi-clock-history\"></i> This Month</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                                                                    <span class=\"price-text fw-bold sm-text\">LKR. 3,150.00</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-1 d-flex align-items-center d-grid\">\r\n");
      out.write("                                                                    <button class=\"view-btn sm-text\">View</button>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"col-6 col-lg-12\">\r\n");
      out.write("                                                    <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                                                        <div class=\"col-12\">\r\n");
      out.write("                                                            <div class=\"row px-3 bg-white mt-2\">\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-1\">\r\n");
      out.write("                                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/products/sony playstation.webp\"\r\n");
      out.write("                                                                         class=\"p-h-product-circle\" alt=\"\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-4 d-flex align-items-center\">\r\n");
      out.write("                                                                    <span class=\"text-truncate sm-text\">Sony Playstation 5 Disc Version Video Game Console</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                                                                    <span class=\"text-black-50 fw-bold sm-text\"><i\r\n");
      out.write("                                                                            class=\"bi bi-clock-history\"></i> This Month</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                                                                    <span class=\"price-text fw-bold sm-text\">LKR. 224,143.00</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-1 d-flex align-items-center d-grid\">\r\n");
      out.write("                                                                    <button class=\"view-btn sm-text\">View</button>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"col-6 col-lg-12\">\r\n");
      out.write("                                                    <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                                                        <div class=\"col-12\">\r\n");
      out.write("                                                            <div class=\"row px-3 bg-white mt-2\">\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-1\">\r\n");
      out.write("                                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/products/fast 60w charger.webp\"\r\n");
      out.write("                                                                         class=\"p-h-product-circle\" alt=\"\">\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-4 d-flex align-items-center\">\r\n");
      out.write("                                                                    <span class=\"text-truncate sm-text\">Fast 60W PD USB Type C to USB Type-C Charge 90 Degree Right Angle Cable UK</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                                                                    <span class=\"text-black-50 fw-bold sm-text\"><i\r\n");
      out.write("                                                                            class=\"bi bi-clock-history\"></i> This Month</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                                                                    <span class=\"price-text fw-bold sm-text\">LKR. 2,392.00</span>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                                <div class=\"col-12 col-lg-1 d-flex align-items-center d-grid\">\r\n");
      out.write("                                                                    <button class=\"view-btn sm-text\">View</button>\r\n");
      out.write("                                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                                    </div>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"col-12 col-lg-4 mt-2\">\r\n");
      out.write("                                            <span class=\"fw-bold\">Visitors</span>\r\n");
      out.write("\r\n");
      out.write("                                            <div class=\"row p-2\">\r\n");
      out.write("                                                <div class=\"col-12 p-2 bg-white text-center\">\r\n");
      out.write("\r\n");
      out.write("                                                    <span class=\"fw-bold d-block mt-2\">Recent Month</span>\r\n");
      out.write("\r\n");
      out.write("                                                    <div class=\"outline-area mt-3\">\r\n");
      out.write("                                                        <div class=\"fill-area d-flex align-items-center justify-content-center shadow\">\r\n");
      out.write("                                                            <div class=\"content-area\">\r\n");
      out.write("\r\n");
      out.write("                                                                <span class=\"d-block fw-bold\"> 90.45%</span>\r\n");
      out.write("                                                                <span class=\"d-block fw-bold text-black-50\"> Website growth</span>\r\n");
      out.write("\r\n");
      out.write("                                                            </div>\r\n");
      out.write("                                                        </div>\r\n");
      out.write("                                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("                                ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <script>\r\n");
      out.write("            $('#summernote').summernote({\r\n");
      out.write("                placeholder: 'Enter your description',\r\n");
      out.write("                tabsize: 2,\r\n");
      out.write("                height: 120,\r\n");
      out.write("                toolbar: [\r\n");
      out.write("                    ['style', ['style']],\r\n");
      out.write("                    ['font', ['bold', 'underline', 'clear']],\r\n");
      out.write("                    ['color', ['color']],\r\n");
      out.write("                    ['para', ['ul', 'ol', 'paragraph']],\r\n");
      out.write("                    ['table', ['table']],\r\n");
      out.write("                    ['insert', ['link', 'picture', 'video']],\r\n");
      out.write("                    ['view', ['fullscreen', 'codeview', 'help']]\r\n");
      out.write("                ]\r\n");
      out.write("            });\r\n");
      out.write("        </script>\r\n");
      out.write("\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
