/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-23 15:58:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class advance_002dsearch_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/DELL/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244248905L));
    _jspx_dependants.put("jar:file:/C:/Users/DELL/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/advance-search.jsp(3,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/advance-search.jsp(5,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      // /WEB-INF/views/frontend/advance-search.jsp(5,4) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setType("REPLACE");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <body>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 py-3 ps-4 mt-4 mt-lg-2\">\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"index.php\" class=\"pagination-links\">Home</a>\r\n");
      out.write("\r\n");
      out.write("                    <span><i class=\"bi bi-chevron-right fs-mini fw-bold\"></i></span>\r\n");
      out.write("\r\n");
      out.write("                    <a class=\"pagination-links\">Products</a>\r\n");
      out.write("\r\n");
      out.write("                    <span><i class=\"bi bi-chevron-right fs-mini fw-bold\"></i></span>\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"purchased-history.php\" class=\"pagination-links active-page\">Advanced Search</a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 my-3 mt-4\">\r\n");
      out.write("                            <span class=\"main-heading\">Advanced Search</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"input-group mb-3 border-dark-outline\">\r\n");
      out.write("                                <input type=\"text\" class=\"form-control\" placeholder=\"Search keyword or name\"\r\n");
      out.write("                                       aria-label=\"Example text with button addon\" aria-describedby=\"button-addon1\">\r\n");
      out.write("                                <button class=\"btn-my-2\" type=\"button\" id=\"button-addon1\"><i class=\"bi bi-search\"></i>\r\n");
      out.write("                                </button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"formGroupExampleInput\" class=\"form-label sm-text fw-bold ms-2\">Kyeword\r\n");
      out.write("                                    Options</label>\r\n");
      out.write("                                <select name=\"\" id=\"\" class=\"form-control\">\r\n");
      out.write("                                    <option value=\"\">All words, any orders</option>\r\n");
      out.write("                                    <option value=\"\">Any words, any orders</option>\r\n");
      out.write("                                    <option value=\"\">Exact words, Exact orders</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"formGroupExampleInput\" class=\"form-label sm-text fw-bold ms-2\">In this\r\n");
      out.write("                                    category</label>\r\n");
      out.write("                                <select name=\"\" id=\"\" class=\"form-control\">\r\n");
      out.write("                                    <option value=\"\">All categories</option>\r\n");
      out.write("                                    <option value=\"\">Electronic devices</option>\r\n");
      out.write("                                    <option value=\"\">Mobile Accessories</option>\r\n");
      out.write("                                    <option value=\"\">Computer Accessories</option>\r\n");
      out.write("                                    <option value=\"\">Camera Accessories</option>\r\n");
      out.write("                                    <option value=\"\">Computer Components</option>\r\n");
      out.write("                                    <option value=\"\">Network Components</option>\r\n");
      out.write("                                    <option value=\"\">Cooling and Heating</option>\r\n");
      out.write("                                    <option value=\"\">Washing Machines</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"formGroupExampleInput\" class=\"form-label sm-text fw-bold ms-2\">In this\r\n");
      out.write("                                    brand</label>\r\n");
      out.write("                                <select name=\"\" id=\"\" class=\"form-control\">\r\n");
      out.write("                                    <option value=\"\">All brands</option>\r\n");
      out.write("                                    <option value=\"\">Apple</option>\r\n");
      out.write("                                    <option value=\"\">Sony</option>\r\n");
      out.write("                                    <option value=\"\">TLC</option>\r\n");
      out.write("                                    <option value=\"\">Huawei</option>\r\n");
      out.write("                                    <option value=\"\">Ushsha</option>\r\n");
      out.write("                                    <option value=\"\">Samsung</option>\r\n");
      out.write("                                    <option value=\"\">Softlogic</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 d-flex justify-content-end\">\r\n");
      out.write("                            <button class=\"serach-btn shadow\">Search</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <hr class=\"my-3\"/>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label class=\"form-label sm-text fw-bold ms-2\">Search including</label>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"flexCheckDefault\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("                                    Title and description\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"flexCheckDefault\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("                                    Completed listings\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"flexCheckDefault\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("                                    Sold listings\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <hr class=\"my-3\"/>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label for=\"formGroupExampleInput\" class=\"form-label sm-text fw-bold ms-2\">Price</label>\r\n");
      out.write("                            <label for=\"formGroupExampleInput\" class=\"form-label sm-text fw-bold ms-2 text-black-50\">Show\r\n");
      out.write("                                items priced from LKR.</label>\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-lg-5\">\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" name=\"\" id=\"\" placeholder=\"LKR 100.00\">\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-lg-2 text-center\">\r\n");
      out.write("                                    <span class=\"sm-text\">to</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-lg-5\">\r\n");
      out.write("                                    <input type=\"text\" class=\"form-control\" name=\"\" id=\"\" placeholder=\"LKR 100,000.00\">\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <hr class=\"my-3\"/>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label for=\"formGroupExampleInput\" class=\"form-label sm-text fw-bold ms-2\">Condition</label>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"flexCheckDefault\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("                                    New\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"flexCheckDefault\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("                                    Used\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"flexCheckDefault\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("                                    Not Specified\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <hr class=\"my-3\"/>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label for=\"formGroupExampleInput\" class=\"form-label sm-text fw-bold ms-2\">Shipping\r\n");
      out.write("                                options</label>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"flexCheckDefault\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("                                    Free international shipping\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <hr class=\"my-3\"/>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <label for=\"formGroupExampleInput\" class=\"form-label sm-text fw-bold ms-2\">Sellers</label>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"form-check\">\r\n");
      out.write("                                <input class=\"form-check-input\" type=\"checkbox\" value=\"\" id=\"flexCheckDefault\">\r\n");
      out.write("                                <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("                                    Only show items from\r\n");
      out.write("                                </label>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row d-flex justify-content-end\">\r\n");
      out.write("                                <div class=\"col-12 col-lg-11 mt-2\">\r\n");
      out.write("                                    <div class=\"mb-3\">\r\n");
      out.write("                                        <div class=\"form-check\">\r\n");
      out.write("                                            <input class=\"form-check-input\" type=\"checkbox\" value=\"\"\r\n");
      out.write("                                                   id=\"flexCheckDefault\">\r\n");
      out.write("                                            <label class=\"form-check-label\" for=\"flexCheckDefault\">\r\n");
      out.write("                                                Specific sellers (enter seller's user IDs)\r\n");
      out.write("                                            </label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <input type=\"text\" class=\"form-control my-1\" id=\"formGroupExampleInput\"\r\n");
      out.write("                                               placeholder=\"Enter seller's user ID\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <hr class=\"my-3\"/>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"formGroupExampleInput\" class=\"form-label sm-text fw-bold ms-2\">Sort\r\n");
      out.write("                                    by</label>\r\n");
      out.write("                                <select name=\"\" id=\"\" class=\"form-control\">\r\n");
      out.write("                                    <option value=\"\">Best match</option>\r\n");
      out.write("                                    <option value=\"\">Price : Low to High</option>\r\n");
      out.write("                                    <option value=\"\">Price : High to Low</option>\r\n");
      out.write("                                    <option value=\"\">Date : Old to Newest</option>\r\n");
      out.write("                                    <option value=\"\">Date : Newest to Old</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"formGroupExampleInput\" class=\"form-label sm-text fw-bold ms-2\">View\r\n");
      out.write("                                    results</label>\r\n");
      out.write("                                <select name=\"\" id=\"\" class=\"form-control\">\r\n");
      out.write("                                    <option value=\"\">All items</option>\r\n");
      out.write("                                    <option value=\"\">Numbers</option>\r\n");
      out.write("                                    <option value=\"\">List</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label for=\"formGroupExampleInput\" class=\"form-label sm-text fw-bold ms-2\">Result per\r\n");
      out.write("                                    page</label>\r\n");
      out.write("                                <select name=\"\" id=\"\" class=\"form-control\">\r\n");
      out.write("                                    <option value=\"\">60</option>\r\n");
      out.write("                                    <option value=\"\">120</option>\r\n");
      out.write("                                    <option value=\"\">240</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <hr class=\"my-3\"/>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 d-flex justify-content-end\">\r\n");
      out.write("                            <button class=\"serach-btn shadow\">Search</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 d-flex justify-content-end mb-3\">\r\n");
      out.write("                            <button class=\"btn-my text-black-50 text-decoration-underline sm-text fw-bold\">Clear\r\n");
      out.write("                                Options\r\n");
      out.write("                            </button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
