/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2024-03-22 10:59:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import org.hibernate.SessionFactory;
import com.apx.radiance.util.HibernateUtil;
import org.hibernate.Session;
import com.apx.radiance.entity.Product;
import java.util.List;
import org.hibernate.query.Query;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/Vidhura/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
    _jspx_dependants.put("file:/C:/Users/Vidhura/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692219573000L));
    _jspx_dependants.put("jar:file:/C:/Users/Vidhura/.m2/repository/org/mortbay/jasper/taglibs-standard/10.0.0-M10/taglibs-standard-10.0.0-M10.jar!/META-INF/c.tld", Long.valueOf(1425958870000L));
    _jspx_dependants.put("file:/C:/Users/Vidhura/.m2/repository/org/mortbay/jasper/taglibs-standard/10.0.0-M10/taglibs-standard-10.0.0-M10.jar", Long.valueOf(1606154388000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.apx.radiance.util.HibernateUtil");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("org.hibernate.query.Query");
    _jspx_imports_classes.add("org.hibernate.Session");
    _jspx_imports_classes.add("com.apx.radiance.entity.Product");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


    SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
    Session openSession = sessionFactory.openSession();

    List<Product> productList = openSession.createQuery("select product from Product product order by product.createdAt desc limit 4", Product.class).getResultList();
    pageContext.setAttribute("productSet", productList);

    Query<Product> eletronicProductQuery = openSession.createQuery("select product from Product product where product.category.name=:name order by product.createdAt desc limit 4", Product.class);
    List<Product> electronicProductList = eletronicProductQuery.setParameter("name", "Electronic Accessories").getResultList();
    pageContext.setAttribute("electronicProductSet", electronicProductList);

    Query<Product> computerProductQuery = openSession.createQuery("select product from Product product where product.category.name=:name order by product.createdAt desc limit 4", Product.class);
    List<Product> computerProductList = computerProductQuery.setParameter("name", "Computer Accessories").getResultList();
    pageContext.setAttribute("computerProductSet", computerProductList);


      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/home.jsp(28,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/home.jsp(30,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      // /WEB-INF/views/frontend/home.jsp(30,4) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setType("REPLACE");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(new jakarta.servlet.jsp.tagext.TagAdapter((jakarta.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/views/frontend/home.jsp(242,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("productList");
      // /WEB-INF/views/frontend/home.jsp(242,24) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/frontend/home.jsp(242,24) '${productSet}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${productSet}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("                            <div class=\"col-6 col-md-4 col-lg-3 p-2\">\r\n");
            out.write("                                <div class=\"crd\">\r\n");
            out.write("\r\n");
            out.write("                                    <div class=\"img-file\">\r\n");
            out.write("\r\n");
            out.write("                                        ");
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("                                    </div>\r\n");
            out.write("\r\n");
            out.write("                                    <div class=\"crd-info pt-2\">\r\n");
            out.write("                                        <h6 class=\"crd-title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6>\r\n");
            out.write("                                        <div class=\"crd-other-details\">\r\n");
            out.write("                                            <span class=\"sold-lst\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.qty+10}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" sold <span class=\"dscnt-p fw-bolder\">NEW</span></span>\r\n");
            out.write("                                            <label class=\"crd-lbl-1 d-none\">New</label>\r\n");
            out.write("                                            <div class=\"starts\">\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-half\"></i>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                            <span class=\"shipping\">Shipping : LKR.");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.delivery_fee.intValue()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".00</span>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                        <div class=\"sub-info\">\r\n");
            out.write("                                            <div class=\"price\"><span\r\n");
            out.write("                                                    class=\"lkr\">LKR.</span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.price.intValue()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<span\r\n");
            out.write("                                                    class=\"lkr\">.00</span>\r\n");
            out.write("                                                <span class=\"dscnt d-block\">LKR. ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.price.intValue()+1000}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".00</span>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                    <div class=\"crd-overlay\">\r\n");
            out.write("                                        <a onclick=\"addToCart(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" style=\"--i:1;\" class=\"bi bi-bag\"></a>\r\n");
            out.write("                                        <a onclick=\"addToWishlist(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" style=\"--i:2;\" class=\"bi bi-heart\"></a>\r\n");
            out.write("                                        <a onclick=\"singleProductView(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" style=\"--i:3;\" class=\"bi bi-eye\"></a>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                </div>\r\n");
            out.write("\r\n");
            out.write("                            </div>\r\n");
            out.write("\r\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new jakarta.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/frontend/home.jsp(249,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("productImage");
      // /WEB-INF/views/frontend/home.jsp(249,40) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/frontend/home.jsp(249,40) '${productList.product_images}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${productList.product_images}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImage.path_01}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new jakarta.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f2(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f2 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f2_reused = false;
    try {
      _jspx_th_c_005fforEach_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f2.setParent(new jakarta.servlet.jsp.tagext.TagAdapter((jakarta.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/views/frontend/home.jsp(405,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setVar("elecProductList");
      // /WEB-INF/views/frontend/home.jsp(405,24) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f2.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/frontend/home.jsp(405,24) '${electronicProductSet}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${electronicProductSet}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f2 = _jspx_th_c_005fforEach_005f2.doStartTag();
        if (_jspx_eval_c_005fforEach_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("                            <div class=\"col-6 col-md-4 col-lg-3 p-2\">\r\n");
            out.write("                                <div class=\"crd\">\r\n");
            out.write("\r\n");
            out.write("                                    <div class=\"img-file\">\r\n");
            out.write("\r\n");
            out.write("                                        ");
            if (_jspx_meth_c_005fforEach_005f3(_jspx_th_c_005fforEach_005f2, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f2))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("                                    </div>\r\n");
            out.write("\r\n");
            out.write("                                    <div class=\"crd-info pt-2\">\r\n");
            out.write("                                        <h6 class=\"crd-title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elecProductList.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6>\r\n");
            out.write("                                        <div class=\"crd-other-details\">\r\n");
            out.write("                                            <span class=\"sold-lst\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elecProductList.qty+10}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" sold <span class=\"dscnt-p\">-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elecProductList.qty+4}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("%</span></span>\r\n");
            out.write("                                            <label class=\"crd-lbl-1 d-none\">New</label>\r\n");
            out.write("                                            <div class=\"starts\">\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-half\"></i>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                            <span class=\"shipping\">Shipping : LKR.");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elecProductList.delivery_fee.intValue()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".00</span>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                        <div class=\"sub-info\">\r\n");
            out.write("                                            <div class=\"price\"><span\r\n");
            out.write("                                                    class=\"lkr\">LKR.</span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elecProductList.price.intValue()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<span\r\n");
            out.write("                                                    class=\"lkr\">.00</span>\r\n");
            out.write("                                                <span class=\"dscnt d-block\">LKR. ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elecProductList.price.intValue()+1000}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".00</span>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                    <div class=\"crd-overlay\">\r\n");
            out.write("                                        <a onclick=\"addToCart(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elecProductList.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" style=\"--i:1;\" class=\"bi bi-bag\"></a>\r\n");
            out.write("                                        <a onclick=\"addToWishlist(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elecProductList.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" style=\"--i:2;\" class=\"bi bi-heart\"></a>\r\n");
            out.write("                                        <a onclick=\"singleProductView(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${elecProductList.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" style=\"--i:3;\" class=\"bi bi-eye\"></a>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                </div>\r\n");
            out.write("\r\n");
            out.write("                            </div>\r\n");
            out.write("\r\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f2.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new jakarta.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f2);
      _jspx_th_c_005fforEach_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f3(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f2, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f2)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f3 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f3_reused = false;
    try {
      _jspx_th_c_005fforEach_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f3.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f2);
      // /WEB-INF/views/frontend/home.jsp(412,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setVar("productImage");
      // /WEB-INF/views/frontend/home.jsp(412,40) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f3.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/frontend/home.jsp(412,40) '${elecProductList.product_images}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${elecProductList.product_images}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f3 = _jspx_th_c_005fforEach_005f3.doStartTag();
        if (_jspx_eval_c_005fforEach_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImage.path_01}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f3.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new jakarta.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f3);
      _jspx_th_c_005fforEach_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f4(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f4 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f4_reused = false;
    try {
      _jspx_th_c_005fforEach_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f4.setParent(new jakarta.servlet.jsp.tagext.TagAdapter((jakarta.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/views/frontend/home.jsp(474,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setVar("computerProductList");
      // /WEB-INF/views/frontend/home.jsp(474,24) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f4.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/frontend/home.jsp(474,24) '${computerProductSet}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${computerProductSet}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f4 = _jspx_th_c_005fforEach_005f4.doStartTag();
        if (_jspx_eval_c_005fforEach_005f4 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("                            <div class=\"col-6 col-md-4 col-lg-3 p-2\">\r\n");
            out.write("                                <div class=\"crd\">\r\n");
            out.write("\r\n");
            out.write("                                    <div class=\"img-file\">\r\n");
            out.write("\r\n");
            out.write("                                        ");
            if (_jspx_meth_c_005fforEach_005f5(_jspx_th_c_005fforEach_005f4, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f4))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("                                    </div>\r\n");
            out.write("\r\n");
            out.write("                                    <div class=\"crd-info pt-2\">\r\n");
            out.write("                                        <h6 class=\"crd-title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computerProductList.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6>\r\n");
            out.write("                                        <div class=\"crd-other-details\">\r\n");
            out.write("                                            <span class=\"sold-lst\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computerProductList.qty+10}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" sold <span class=\"dscnt-p\">-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computerProductList.qty+4}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("%</span></span>\r\n");
            out.write("                                            <label class=\"crd-lbl-1 d-none\">New</label>\r\n");
            out.write("                                            <div class=\"starts\">\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-half\"></i>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                            <span class=\"shipping\">Shipping : LKR.");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computerProductList.delivery_fee.intValue()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".00</span>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                        <div class=\"sub-info\">\r\n");
            out.write("                                            <div class=\"price\"><span\r\n");
            out.write("                                                    class=\"lkr\">LKR.</span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computerProductList.price.intValue()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<span\r\n");
            out.write("                                                    class=\"lkr\">.00</span>\r\n");
            out.write("                                                <span class=\"dscnt d-block\">LKR. ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computerProductList.price.intValue()+1000}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".00</span>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                    <div class=\"crd-overlay\">\r\n");
            out.write("                                        <a onclick=\"addToCart(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computerProductList.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" style=\"--i:1;\" class=\"bi bi-bag\"></a>\r\n");
            out.write("                                        <a onclick=\"addToWishlist(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computerProductList.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" style=\"--i:2;\" class=\"bi bi-heart\"></a>\r\n");
            out.write("                                        <a onclick=\"singleProductView(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${computerProductList.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" style=\"--i:3;\" class=\"bi bi-eye\"></a>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                </div>\r\n");
            out.write("\r\n");
            out.write("                            </div>\r\n");
            out.write("\r\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f4.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f4.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new jakarta.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f4);
      _jspx_th_c_005fforEach_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f5(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f4, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f4)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f5 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f5_reused = false;
    try {
      _jspx_th_c_005fforEach_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f5.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f4);
      // /WEB-INF/views/frontend/home.jsp(481,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setVar("productImage");
      // /WEB-INF/views/frontend/home.jsp(481,40) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f5.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/frontend/home.jsp(481,40) '${computerProductList.product_images}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${computerProductList.product_images}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f5 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f5 = _jspx_th_c_005fforEach_005f5.doStartTag();
        if (_jspx_eval_c_005fforEach_005f5 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImage.path_01}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f5.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f5.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new jakarta.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f5[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f5.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f5.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f5);
      _jspx_th_c_005fforEach_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f5_reused);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <body onload=\"offerTimer();\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"side-menu d-none d-lg-flex align-items-center shadow\">\r\n");
      out.write("                    <div class=\"div\">\r\n");
      out.write("                        <button class=\"d-block side-menu-btns\"><i class=\"bi bi-bag\"></i></button>\r\n");
      out.write("                        <button class=\"d-block side-menu-btns\"><i class=\"bi bi-heart\"></i></button>\r\n");
      out.write("                        <button class=\"d-block side-menu-btns\"><i class=\"bi bi-clock-history\"></i></button>\r\n");
      out.write("                        <button class=\"d-block side-menu-btns\"><i class=\"bi bi-bell-slash\"></i></button>\r\n");
      out.write("                        <button class=\"d-block side-menu-btns\"><i class=\"bi bi-share\"></i></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1 mt-3\">\r\n");
      out.write("                    <div class=\"row padding-sm\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-3 bg-white rounded-cornrs d-none d-xl-block\">\r\n");
      out.write("                            <div class=\"row category-area\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 p-3\">\r\n");
      out.write("                                    <span class=\"fw-bold\"><i class=\"bi bi-grid me-3\"></i> Categories</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                    <span class=\"ps-1 text-black-50\"><i class=\"bi bi-phone-vibrate me-3\"></i> Electronic Devices</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                    <span class=\"ps-1 text-black-50\"><i class=\"bi bi-phone me-3\"></i> Mobile Accessories</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                    <span class=\"ps-1 text-black-50\"><i class=\"bi bi-display me-3\"></i> Computer Accessories</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                    <span class=\"ps-1 text-black-50\"><i class=\"bi bi-camera me-3\"></i> Camera Accessories</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                    <span class=\"ps-1 text-black-50\"><i class=\"bi bi-pc-display me-3\"></i> Computer Components</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                    <span class=\"ps-1 text-black-50\"><i class=\"bi bi-hdd-network me-3\"></i> Network Components</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                    <span class=\"ps-1 text-black-50\"><i class=\"bi bi-tv me-3\"></i> TV and Video Devices</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                    <span class=\"ps-1 text-black-50\"><i class=\"bi bi-door-closed me-3\"></i> Cooling and Heating</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                    <span class=\"ps-1 text-black-50\"><i class=\"bi bi-safe2 me-3\"></i> Washing Machines</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-xl-9 slider-area\">\r\n");
      out.write("                            <div id=\"carouselExampleCaptions\" class=\"carousel slide carousel-fade\" data-bs-ride=\"carousel\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"carousel-inner\">\r\n");
      out.write("                                    <div class=\"carousel-item active\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/slider/s01.jpg\" class=\"d-block w-100 rounded-cornrs\" alt=\"...\">\r\n");
      out.write("                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"carousel-item\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/slider/s02.jpg\" class=\"d-block w-100 rounded-cornrs\" alt=\"...\">\r\n");
      out.write("                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"carousel-item\">\r\n");
      out.write("                                        <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/slider/s03.jpg\" class=\"d-block w-100 rounded-cornrs\" alt=\"...\">\r\n");
      out.write("                                        <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <button class=\"carousel-control-prev\">\r\n");
      out.write("                                    <span class=\"carousel-control-prev-icon\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"prev\" aria-hidden=\"true\"><i class=\"bi bi-chevron-left\"></i></span>\r\n");
      out.write("                                    <span class=\"visually-hidden\">Previous</span>\r\n");
      out.write("                                </button>\r\n");
      out.write("                                <button class=\"carousel-control-next\">\r\n");
      out.write("                                    <span class=\"carousel-control-next-icon\" type=\"button\" data-bs-target=\"#carouselExampleCaptions\" data-bs-slide=\"next\" aria-hidden=\"true\"><i class=\"bi bi-chevron-right\"></i></span>\r\n");
      out.write("                                    <span class=\"visually-hidden\">Next</span>\r\n");
      out.write("                                </button>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mt-4 d-block d-lg-none\">\r\n");
      out.write("                    <div class=\"row bg-dark text-white p-2\">\r\n");
      out.write("                        <div class=\"col-10\">\r\n");
      out.write("                            <span><span class=\"fw-bold\"><i class=\"bi bi-grid me-3\"></i> Categories</span></span>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-2 d-flex justify-content-end\">\r\n");
      out.write("                            <button class=\"menu-btn text-white\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#categories\" aria-controls=\"offcanvasExample\"><i class=\"bi bi-justify-right fs-4\"></i></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- off canvas -->\r\n");
      out.write("                <div class=\"offcanvas offcanvas-start\" tabindex=\"-1\" id=\"categories\" aria-labelledby=\"offcanvasExampleLabel\">\r\n");
      out.write("                    <div class=\"offcanvas-header\">\r\n");
      out.write("                        <h5 class=\"offcanvas-title\" id=\"offcanvasExampleLabel\">Categories</h5>\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close text-reset\" data-bs-dismiss=\"offcanvas\" aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"offcanvas-body\">\r\n");
      out.write("                        <div class=\"row category-area\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                <span class=\"ps-1 text-black-50\"><i class=\"bi bi-phone-vibrate me-3\"></i> Electronic Devices</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                <span class=\"ps-1 text-black-50\"><i class=\"bi bi-phone me-3\"></i> Mobile Accessories</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                <span class=\"ps-1 text-black-50\"><i class=\"bi bi-display me-3\"></i> Computer Accessories</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                <span class=\"ps-1 text-black-50\"><i class=\"bi bi-camera me-3\"></i> Camera Accessories</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                <span class=\"ps-1 text-black-50\"><i class=\"bi bi-pc-display me-3\"></i> Computer Components</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                <span class=\"ps-1 text-black-50\"><i class=\"bi bi-hdd-network me-3\"></i> Network Components</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                <span class=\"ps-1 text-black-50\"><i class=\"bi bi-tv me-3\"></i> TV and Video Devices</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                <span class=\"ps-1 text-black-50\"><i class=\"bi bi-door-closed me-3\"></i> Cooling and Heating</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 py-1 py-xxl-2 pt-2 pt-xxl-2\">\r\n");
      out.write("                                <span class=\"ps-1 text-black-50\"><i class=\"bi bi-safe2 me-3\"></i> Washing Machines</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- off canvas -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1 mt-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-4\">\r\n");
      out.write("                            <img src=\"assets/pictures/posters/sm-banner-01.jpg\" class=\"posters shadow\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-4\">\r\n");
      out.write("                            <img src=\"assets/pictures/posters/sm-banner-02.jpg\" class=\"posters shadow\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-4\">\r\n");
      out.write("                            <img src=\"assets/pictures/posters/sm-banner-03.jpg\" class=\"posters shadow\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1 mt-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-4\">\r\n");
      out.write("                            <div class=\"sale-countdown\">\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <span class=\"coundwn-timer-txt\">On sale now</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"timer\">\r\n");
      out.write("                                    <span class=\"sm-text d-inline-block text-black ms-2 me-2\">Ending in </span>\r\n");
      out.write("                                    <div class=\"timer-details shadow\" id=\"days\"></div> :\r\n");
      out.write("                                    <div class=\"timer-details shadow\" id=\"hour\"></div> :\r\n");
      out.write("                                    <div class=\"timer-details shadow\" id=\"min\"></div> :\r\n");
      out.write("                                    <div class=\"timer-details shadow\" id=\"secounds\"></div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-2 d-block d-lg-none\"></div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-8 col-lg-4 text-center mt-4\">\r\n");
      out.write("                            <span class=\"main-heading\">New <span class=\"main-heading clr\"> Arrivals</span></span>\r\n");
      out.write("                            <div class=\"underline-mn\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-2 col-lg-4 mt-4 d-flex justify-content-end pe-4\">\r\n");
      out.write("                            <button class=\"more-btn\">More <i class=\"bi bi-chevron-right ms-2 rght-arw\"></i></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- new arrivals -->\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1 mt-3\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mt-4 pb-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12 offset-lg-1 col-lg-10\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-md-3 text-center p-3 text-black-50\">\r\n");
      out.write("                                    <span class=\"d-block\"><i class=\"bi bi-cash big-icon\"></i></span>\r\n");
      out.write("                                    <span class=\"d-block fw-bold\">Great Value</span>\r\n");
      out.write("                                    <span class=\"d-block\">We offer competitive prices on our 100 million plus product range.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-md-3 text-center p-3 text-black-50\">\r\n");
      out.write("                                    <span class=\"d-block\"><i class=\"bi bi-wallet2 big-icon\"></i></span>\r\n");
      out.write("                                    <span class=\"d-block fw-bold\">Safe Payment</span>\r\n");
      out.write("                                    <span class=\"d-block\">Pay with the worlds most popular and secure payment methods.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-md-3 text-center p-3 text-black-50\">\r\n");
      out.write("                                    <span class=\"d-block\"><i class=\"bi bi-shield-check big-icon\"></i></span>\r\n");
      out.write("                                    <span class=\"d-block fw-bold\">Shop with confidence</span>\r\n");
      out.write("                                    <span class=\"d-block\">Our Buyer Protection covers your purchase from click to delivery.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-md-3 text-center p-3 text-black-50\">\r\n");
      out.write("                                    <span class=\"d-block\"><i class=\"bi bi-telephone big-icon\"></i></span>\r\n");
      out.write("                                    <span class=\"d-block fw-bold\">Help Center</span>\r\n");
      out.write("                                    <span class=\"d-block\">Round-the-clock assistance for a smooth shopping experience.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1 mt-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-3\">\r\n");
      out.write("                            <img src=\"assets/pictures/posters/banner-7.jpg\" class=\"posters shadow\" alt=\"\">\r\n");
      out.write("                            <img src=\"assets/pictures/posters/banner-8.jpg\" class=\"posters shadow mt-4\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-3\">\r\n");
      out.write("                            <img src=\"assets/pictures/posters/poster 13.jpg\" class=\"posters shadow\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-3\">\r\n");
      out.write("                            <img src=\"assets/pictures/posters/poster 12.jpg\" class=\"posters shadow\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-3\">\r\n");
      out.write("                            <img src=\"assets/pictures/posters/poster 09.jpg\" class=\"posters shadow\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- electronic devices -->\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-2 col-lg-4 mt-4 d-flex justify-content-end pe-4\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-8 col-lg-4 text-center mt-5\">\r\n");
      out.write("                            <span class=\"main-heading\">Electronic<span class=\"main-heading clr\"> Devices</span></span>\r\n");
      out.write("                            <div class=\"underline-mn\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-2 col-lg-4 mt-5 d-flex justify-content-end pe-4\">\r\n");
      out.write("                            <button class=\"more-btn\">More <i class=\"bi bi-chevron-right ms-2 rght-arw\"></i></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1 mt-3\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f2(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- computer devices -->\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-2 col-lg-4 mt-4 d-flex justify-content-end pe-4\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-8 col-lg-4 text-center mt-5\">\r\n");
      out.write("                            <span class=\"main-heading\">Computers and <span class=\"main-heading clr\"> Accessories</span></span>\r\n");
      out.write("                            <div class=\"underline-mn\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-2 col-lg-4 mt-5 d-flex justify-content-end pe-4\">\r\n");
      out.write("                            <button class=\"more-btn\">More <i class=\"bi bi-chevron-right ms-2 rght-arw\"></i></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1 mt-3\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f4(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1 mt-4 d-none d-xl-block\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-3\">\r\n");
      out.write("                            <img src=\"assets/pictures/posters/poster 11.jpg\" class=\"posters shadow\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-9\">\r\n");
      out.write("                            <img src=\"assets/pictures/posters/poster 10.jpg\" class=\"posters shadow\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 bg-white mt-4 pb-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12 offset-lg-1 col-lg-10\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 text-black-50 text-center big-icon\">\r\n");
      out.write("                                    <span class=\"\">Introducing our NEW online store with more ways to explore your favourite iteams</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-md-3 text-center bg-white p-3 text-black-50\">\r\n");
      out.write("                                    <span class=\"d-block\"><i class=\"bi bi-cash big-icon\"></i></span>\r\n");
      out.write("                                    <span class=\"d-block fw-bold\">Great Value</span>\r\n");
      out.write("                                    <span class=\"d-block\">We offer competitive prices on our 100 million plus product range.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-md-3 text-center bg-white p-3 text-black-50\">\r\n");
      out.write("                                    <span class=\"d-block\"><i class=\"bi bi-wallet2 big-icon\"></i></span>\r\n");
      out.write("                                    <span class=\"d-block fw-bold\">Safe Payment</span>\r\n");
      out.write("                                    <span class=\"d-block\">Pay with the worlds most popular and secure payment methods.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-md-3 text-center bg-white p-3 text-black-50\">\r\n");
      out.write("                                    <span class=\"d-block\"><i class=\"bi bi-shield-check big-icon\"></i></span>\r\n");
      out.write("                                    <span class=\"d-block fw-bold\">Shop with confidence</span>\r\n");
      out.write("                                    <span class=\"d-block\">Our Buyer Protection covers your purchase from click to delivery.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"col-12 col-md-3 text-center bg-white p-3 text-black-50\">\r\n");
      out.write("                                    <span class=\"d-block\"><i class=\"bi bi-telephone big-icon\"></i></span>\r\n");
      out.write("                                    <span class=\"d-block fw-bold\">Help Center</span>\r\n");
      out.write("                                    <span class=\"d-block\">Round-the-clock assistance for a smooth shopping experience.</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        </body>\r\n");
      out.write("\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
