/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2023-09-23 17:31:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class purchased_002dhistory_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("file:/C:/Users/DELL/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692244248905L));
    _jspx_dependants.put("jar:file:/C:/Users/DELL/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/purchased-history.jsp(3,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/purchased-history.jsp(5,2) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      // /WEB-INF/views/frontend/purchased-history.jsp(5,2) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setType("REPLACE");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <body>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 py-3 ps-4 mt-4 mt-lg-2\">\r\n");
      out.write("\r\n");
      out.write("          <a href=\"index.php\" class=\"pagination-links\">Home</a>\r\n");
      out.write("\r\n");
      out.write("          <span><i class=\"bi bi-chevron-right fs-mini fw-bold\"></i></span>\r\n");
      out.write("\r\n");
      out.write("          <a class=\"pagination-links\">My Account</a>\r\n");
      out.write("\r\n");
      out.write("          <span><i class=\"bi bi-chevron-right fs-mini fw-bold\"></i></span>\r\n");
      out.write("\r\n");
      out.write("          <a href=\"purchased-history.php\" class=\"pagination-links active-page\">Purchased History</a>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 col-lg-10 offset-lg-1 my-2\">\r\n");
      out.write("          <span class=\"main-heading\">Purchased History</span>\r\n");
      out.write("\r\n");
      out.write("          <ul class=\"nav nav-tabs mt-2\" id=\"myTab\" role=\"tablist\">\r\n");
      out.write("            <li class=\"nav-item me-2 ms-4\" role=\"presentation\">\r\n");
      out.write("              <button class=\"nav-link active\" id=\"home-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#all\" type=\"button\" role=\"tab\" aria-controls=\"home\" aria-selected=\"true\">All Items</button>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item me-2\" role=\"presentation\">\r\n");
      out.write("              <button class=\"nav-link\" id=\"profile-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#completed\" type=\"button\" role=\"tab\" aria-controls=\"profile\" aria-selected=\"false\">Completed</button>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item me-2\" role=\"presentation\">\r\n");
      out.write("              <button class=\"nav-link\" id=\"contact-tab\" data-bs-toggle=\"tab\" data-bs-target=\"#cancel\" type=\"button\" role=\"tab\" aria-controls=\"contact\" aria-selected=\"false\">Canceled</button>\r\n");
      out.write("            </li>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-12 col-lg-8 mt-3 mt-lg-0\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-6\">\r\n");
      out.write("                  <div class=\"input-group mb-3 border-dark-outline\">\r\n");
      out.write("                    <input type=\"text\" class=\"form-control\" placeholder=\"Search..\" aria-label=\"Example text with button addon\" aria-describedby=\"button-addon1\">\r\n");
      out.write("                    <button class=\"btn-my-2\" type=\"button\" id=\"button-addon1\"><i class=\"bi bi-search\"></i></button>\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-6 mb-2 mb-lg-0\">\r\n");
      out.write("                  <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-5\">\r\n");
      out.write("                      <input class=\"form-control\" type=\"date\" value=\"05/09/2022\" placeholder=\"Default input\" aria-label=\"default input example\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-2 text-center d-flex align-items-center justify-content-center\">\r\n");
      out.write("                      <span class=\"text-black-50 fw-bold\">to</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-5\">\r\n");
      out.write("                      <input class=\"form-control\" type=\"date\" value=\"05/09/2022\" placeholder=\"Default input\" aria-label=\"default input example\">\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </ul>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"tab-content\" id=\"myTabContent\">\r\n");
      out.write("            <div class=\"tab-pane fade show active\" id=\"all\" role=\"tabpanel\" aria-labelledby=\"home-tab\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-6 col-lg-12\">\r\n");
      out.write("                  <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <div class=\"row p-2 bg-white mt-2 rounded-cornrs\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"># 235264</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1\">\r\n");
      out.write("                          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/products/ele 01.webp\" class=\"p-h-product-circle\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-truncate\">LED Recessed Spotlight 10W/12W/14W CCT Dimmable Spotlight Ceiling Spot 230V IP44 Round</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">Completed</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"><i class=\"bi bi-clock-history\"></i> 2 days ago</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">LKR. 11,250.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center d-grid\">\r\n");
      out.write("                          <button class=\"view-btn\">View</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-6 col-lg-12\">\r\n");
      out.write("                  <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <div class=\"row p-2 bg-white mt-2 rounded-cornrs\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"># 212364</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1\">\r\n");
      out.write("                          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/products/sony playstation.webp\" class=\"p-h-product-circle\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-truncate\">Sony Playstation 5 Disc Version Video Game Console</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">Completed</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"><i class=\"bi bi-clock-history\"></i> 5 days ago</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">LKR. 224,143.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center d-grid\">\r\n");
      out.write("                          <button class=\"view-btn\">View</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-6 col-lg-12\">\r\n");
      out.write("                  <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <div class=\"row p-2 bg-white mt-2 rounded-cornrs\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"># 125264</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1\">\r\n");
      out.write("                          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/products/wifi display.jpg\" class=\"p-h-product-circle\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-truncate\">Wifi Wireless HDMI Mirror Screen Display Adapter For 1080P TV Miracast Dongle</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">Completed</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"><i class=\"bi bi-clock-history\"></i> 8 days ago</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">LKR. 5,040.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center d-grid\">\r\n");
      out.write("                          <button class=\"view-btn\">View</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-6 col-lg-12\">\r\n");
      out.write("                  <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <div class=\"row p-2 bg-white mt-2 rounded-cornrs\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"># 234457</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1\">\r\n");
      out.write("                          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/products/fast 60w charger.webp\" class=\"p-h-product-circle\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-truncate\">Fast 60W PD USB Type C to USB Type-C Charge 90 Degree Right Angle Cable UK</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">Completed</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"><i class=\"bi bi-clock-history\"></i> 12 days ago</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">LKR. 2,392.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center d-grid\">\r\n");
      out.write("                          <button class=\"view-btn\">View</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 d-flex justify-content-center pt-3\">\r\n");
      out.write("\r\n");
      out.write("                  <nav aria-label=\"Page navigation example\">\r\n");
      out.write("                    <ul class=\"pagination\">\r\n");
      out.write("\r\n");
      out.write("                      <li class=\"page-item\">\r\n");
      out.write("                        <a class=\"page-link\" href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("                          <span aria-hidden=\"true\"><i class=\"bi bi-chevron-left\"></i></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </li>\r\n");
      out.write("\r\n");
      out.write("                      <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                      <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("                      <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("\r\n");
      out.write("                      <li class=\"page-item\">\r\n");
      out.write("                        <a class=\"page-link\" href=\"#\" aria-label=\"Next\">\r\n");
      out.write("                          <span aria-hidden=\"true\"><i class=\"bi bi-chevron-right\"></i></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </li>\r\n");
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </nav>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"tab-pane fade\" id=\"completed\" role=\"tabpanel\" aria-labelledby=\"profile-tab\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-6 col-lg-12\">\r\n");
      out.write("                  <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <div class=\"row p-2 bg-white mt-2 rounded-cornrs\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"># 235264</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1\">\r\n");
      out.write("                          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/products/ele 01.webp\" class=\"p-h-product-circle\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-truncate\">LED Recessed Spotlight 10W/12W/14W CCT Dimmable Spotlight Ceiling Spot 230V IP44 Round</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">Completed</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"><i class=\"bi bi-clock-history\"></i> 2 days ago</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">LKR. 11,250.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center d-grid\">\r\n");
      out.write("                          <button class=\"view-btn\">View</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-6 col-lg-12\">\r\n");
      out.write("                  <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <div class=\"row p-2 bg-white mt-2 rounded-cornrs\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"># 212364</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1\">\r\n");
      out.write("                          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/products/sony playstation.webp\" class=\"p-h-product-circle\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-truncate\">Sony Playstation 5 Disc Version Video Game Console</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">Completed</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"><i class=\"bi bi-clock-history\"></i> 5 days ago</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">LKR. 224,143.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center d-grid\">\r\n");
      out.write("                          <button class=\"view-btn\">View</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-6 col-lg-12\">\r\n");
      out.write("                  <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <div class=\"row p-2 bg-white mt-2 rounded-cornrs\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"># 125264</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1\">\r\n");
      out.write("                          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/products/wifi display.jpg\" class=\"p-h-product-circle\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-truncate\">Wifi Wireless HDMI Mirror Screen Display Adapter For 1080P TV Miracast Dongle</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">Completed</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"><i class=\"bi bi-clock-history\"></i> 8 days ago</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">LKR. 5,040.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center d-grid\">\r\n");
      out.write("                          <button class=\"view-btn\">View</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-6 col-lg-12\">\r\n");
      out.write("                  <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <div class=\"row p-2 bg-white mt-2 rounded-cornrs\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"># 234457</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1\">\r\n");
      out.write("                          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/products/fast 60w charger.webp\" class=\"p-h-product-circle\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-truncate\">Fast 60W PD USB Type C to USB Type-C Charge 90 Degree Right Angle Cable UK</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">Completed</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"><i class=\"bi bi-clock-history\"></i> 12 days ago</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">LKR. 2,392.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center d-grid\">\r\n");
      out.write("                          <button class=\"view-btn\">View</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 d-flex justify-content-center pt-3\">\r\n");
      out.write("\r\n");
      out.write("                  <nav aria-label=\"Page navigation example\">\r\n");
      out.write("                    <ul class=\"pagination\">\r\n");
      out.write("\r\n");
      out.write("                      <li class=\"page-item\">\r\n");
      out.write("                        <a class=\"page-link\" href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("                          <span aria-hidden=\"true\"><i class=\"bi bi-chevron-left\"></i></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </li>\r\n");
      out.write("\r\n");
      out.write("                      <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("                      <li class=\"page-item\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("                      <li class=\"page-item\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("\r\n");
      out.write("                      <li class=\"page-item\">\r\n");
      out.write("                        <a class=\"page-link\" href=\"#\" aria-label=\"Next\">\r\n");
      out.write("                          <span aria-hidden=\"true\"><i class=\"bi bi-chevron-right\"></i></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </li>\r\n");
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </nav>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"tab-pane fade\" id=\"cancel\" role=\"tabpanel\" aria-labelledby=\"contact-tab\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-6 col-lg-12\">\r\n");
      out.write("                  <div class=\"row p-1\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <div class=\"row p-2 bg-white mt-2 rounded-cornrs\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"># 554477</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1\">\r\n");
      out.write("                          <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/products/hdmi port.jpg\" class=\"p-h-product-circle\" alt=\"\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-3 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-truncate\">HDMI Male To VGA Male Video Converter Adapter Cable For PC DVD 1080P HDTV 6FT</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold text-danger\">Canceled</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"text-black-50 fw-bold\"><i class=\"bi bi-clock-history\"></i> 2 days ago</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-2 d-flex align-items-center\">\r\n");
      out.write("                          <span class=\"price-text fw-bold\">LKR. 3,150.00</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 col-lg-1 d-flex align-items-center d-grid\">\r\n");
      out.write("                          <button class=\"view-btn\">View</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                  </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 d-flex justify-content-center pt-3\">\r\n");
      out.write("\r\n");
      out.write("                  <nav aria-label=\"Page navigation example\">\r\n");
      out.write("                    <ul class=\"pagination\">\r\n");
      out.write("\r\n");
      out.write("                      <li class=\"page-item\">\r\n");
      out.write("                        <a class=\"page-link\" href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("                          <span aria-hidden=\"true\"><i class=\"bi bi-chevron-left\"></i></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </li>\r\n");
      out.write("\r\n");
      out.write("                      <li class=\"page-item\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("\r\n");
      out.write("                      <li class=\"page-item\">\r\n");
      out.write("                        <a class=\"page-link\" href=\"#\" aria-label=\"Next\">\r\n");
      out.write("                          <span aria-hidden=\"true\"><i class=\"bi bi-chevron-right\"></i></span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                      </li>\r\n");
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("                  </nav>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    </body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
