/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2024-03-23 10:04:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.frontend;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import org.hibernate.SessionFactory;
import com.apx.radiance.util.HibernateUtil;
import org.hibernate.Session;
import com.apx.radiance.entity.Product;
import java.util.List;
import org.hibernate.query.Query;
import com.apx.radiance.entity.Product_Image;
import java.util.Set;
import java.util.Iterator;

public final class single_002dproduct_002dview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/Vidhura/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
    _jspx_dependants.put("file:/C:/Users/Vidhura/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692219573000L));
    _jspx_dependants.put("jar:file:/C:/Users/Vidhura/.m2/repository/org/mortbay/jasper/taglibs-standard/10.0.0-M10/taglibs-standard-10.0.0-M10.jar!/META-INF/c.tld", Long.valueOf(1425958870000L));
    _jspx_dependants.put("file:/C:/Users/Vidhura/.m2/repository/org/mortbay/jasper/taglibs-standard/10.0.0-M10/taglibs-standard-10.0.0-M10.jar", Long.valueOf(1606154388000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("com.apx.radiance.util.HibernateUtil");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("org.hibernate.query.Query");
    _jspx_imports_classes.add("org.hibernate.Session");
    _jspx_imports_classes.add("com.apx.radiance.entity.Product_Image");
    _jspx_imports_classes.add("java.util.Set");
    _jspx_imports_classes.add("com.apx.radiance.entity.Product");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


    String pid = request.getParameter("pid");

    SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
    Session openSession = sessionFactory.openSession();

    Query<Product> productQuery = openSession.createQuery("select product from Product product where product.id=:productId", Product.class);
    Product productData = productQuery.setParameter("productId", pid).getSingleResult();
    pageContext.setAttribute("products", productData);

    Set<Product_Image> productImages = productData.getProduct_images();
    Iterator<Product_Image> productIterator = productImages.iterator();
    while (productIterator.hasNext()) {
        Product_Image productImage = productIterator.next();

        pageContext.setAttribute("productImages", productImage);
    }

    Query<Product> relatedProductQuery = openSession.createQuery("select p from Product p where p.category.id=:categoryId order by p.createdAt desc limit 4", Product.class);
    List<Product> rProductList = relatedProductQuery.setParameter("categoryId", productData.getCategory().getId()).getResultList();
    pageContext.setAttribute("relatedProductSet", rProductList);


      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_layout_005fextends_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fextends_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:extends
    lk.callidora.jsp.inheritance.ExtendsTag _jspx_th_layout_005fextends_005f0 = new lk.callidora.jsp.inheritance.ExtendsTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fextends_005f0);
    try {
      _jspx_th_layout_005fextends_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/frontend/single-product-view.jsp(38,0) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fextends_005f0.setName("base");
      _jspx_th_layout_005fextends_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_layout_005fextends_005f0, null));
      _jspx_th_layout_005fextends_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fextends_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_layout_005fput_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  layout:put
    lk.callidora.jsp.inheritance.PutTag _jspx_th_layout_005fput_005f0 = new lk.callidora.jsp.inheritance.PutTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fput_005f0);
    try {
      _jspx_th_layout_005fput_005f0.setJspContext(_jspx_page_context);
      _jspx_th_layout_005fput_005f0.setParent(_jspx_parent);
      // /WEB-INF/views/frontend/single-product-view.jsp(40,4) name = block type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setBlock("contents");
      // /WEB-INF/views/frontend/single-product-view.jsp(40,4) name = type type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fput_005f0.setType("REPLACE");
      _jspx_th_layout_005fput_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_layout_005fput_005f0, null));
      _jspx_th_layout_005fput_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fput_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(jakarta.servlet.jsp.tagext.JspTag _jspx_parent, jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(new jakarta.servlet.jsp.tagext.TagAdapter((jakarta.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/views/frontend/single-product-view.jsp(254,24) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("productList");
      // /WEB-INF/views/frontend/single-product-view.jsp(254,24) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/frontend/single-product-view.jsp(254,24) '${relatedProductSet}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${relatedProductSet}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("                            <div class=\"col-6 col-md-4 col-lg-3 p-2\">\r\n");
            out.write("                                <div class=\"crd\">\r\n");
            out.write("\r\n");
            out.write("                                    <div class=\"img-file\">\r\n");
            out.write("\r\n");
            out.write("                                        ");
            if (_jspx_meth_c_005fforEach_005f1(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("\r\n");
            out.write("                                    </div>\r\n");
            out.write("\r\n");
            out.write("                                    <div class=\"crd-info pt-2\">\r\n");
            out.write("                                        <h6 class=\"crd-title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</h6>\r\n");
            out.write("                                        <div class=\"crd-other-details\">\r\n");
            out.write("                                            <span class=\"sold-lst\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.qty+10}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(" sold <span\r\n");
            out.write("                                                    class=\"dscnt-p\">-");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.qty+4}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("%</span></span>\r\n");
            out.write("                                            <label class=\"crd-lbl-1 d-none\">New</label>\r\n");
            out.write("                                            <div class=\"starts\">\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-fill\"></i>\r\n");
            out.write("                                                <i class=\"bi bi-star-half\"></i>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                            <span class=\"shipping\">Shipping : LKR.");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.delivery_fee.intValue()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".00</span>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                        <div class=\"sub-info\">\r\n");
            out.write("                                            <div class=\"price\"><span\r\n");
            out.write("                                                    class=\"lkr\">LKR.</span>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.price.intValue()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("<span\r\n");
            out.write("                                                    class=\"lkr\">.00</span>\r\n");
            out.write("                                                <span class=\"dscnt d-block\">LKR. ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.price.intValue()+1000}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(".00</span>\r\n");
            out.write("                                            </div>\r\n");
            out.write("                                        </div>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                    <div class=\"crd-overlay\">\r\n");
            out.write("                                        <a onclick=\"addToCart(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" style=\"--i:1;\" class=\"bi bi-bag\"></a>\r\n");
            out.write("                                        <a onclick=\"addToWishlist(");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write(");\" href=\"\" style=\"--i:2;\"\r\n");
            out.write("                                           class=\"bi bi-heart\"></a>\r\n");
            out.write("                                        <a href=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("single-product-view?pid=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productList.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" style=\"--i:3;\"\r\n");
            out.write("                                           class=\"bi bi-eye\"></a>\r\n");
            out.write("                                    </div>\r\n");
            out.write("                                </div>\r\n");
            out.write("\r\n");
            out.write("                            </div>\r\n");
            out.write("\r\n");
            out.write("                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new jakarta.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(jakarta.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, jakarta.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent((jakarta.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/frontend/single-product-view.jsp(261,40) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("productImage");
      // /WEB-INF/views/frontend/single-product-view.jsp(261,40) name = items type = jakarta.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/frontend/single-product-view.jsp(261,40) '${productList.product_images}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${productList.product_images}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                            <img src=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImage.path_01}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("                                        ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          throw new jakarta.servlet.jsp.SkipPageException();
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private jakarta.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, jakarta.servlet.jsp.JspContext jspContext, jakarta.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fput_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      return false;
    }
    public boolean invoke1( jakarta.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <body>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 py-3 ps-4 main-background mt-4\">\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"index.php\" class=\"pagination-links\">Home</a>\r\n");
      out.write("\r\n");
      out.write("                    <span><i class=\"bi bi-chevron-right fs-mini fw-bold\"></i></span>\r\n");
      out.write("\r\n");
      out.write("                    <a class=\"pagination-links\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products.category.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("                    <span><i class=\"bi bi-chevron-right fs-mini fw-bold\"></i></span>\r\n");
      out.write("\r\n");
      out.write("                    <a href=\"\" class=\"pagination-links active-page\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12\">\r\n");
      out.write("                    <div class=\"row mt-3 bg-white py-2\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-lg-5\">\r\n");
      out.write("\r\n");
      out.write("                            <img class=\"mainThumbImage mt-2\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages.path_01}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"mainimg\"/>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row mb-2 mt-4\">\r\n");
      out.write("                                <div class=\"col-12 d-none d-lg-block\">\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages.path_01}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"pimg1\"\r\n");
      out.write("                                         onclick=\"loadmainimg(1);\" class=\"border border-1 thumb-imgs\"/>\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages.path_02}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"pimg2\"\r\n");
      out.write("                                         onclick=\"loadmainimg(2);\" class=\"border border-1 thumb-imgs\"/>\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages.path_03}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"pimg3\"\r\n");
      out.write("                                         onclick=\"loadmainimg(3);\" class=\"border border-1 thumb-imgs\"/>\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages.path_04}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"pimg4\"\r\n");
      out.write("                                         onclick=\"loadmainimg(4);\" class=\"border border-1 thumb-imgs\"/>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-12 d-lg-none\">\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages.path_01}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"pimg1\"\r\n");
      out.write("                                         onclick=\"loadmainimg(1);\" class=\"border border-1 thumb-imgs\"/>\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages.path_02}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"pimg2\"\r\n");
      out.write("                                         onclick=\"loadmainimg(2);\" class=\"border border-1 thumb-imgs\"/>\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages.path_03}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"pimg3\"\r\n");
      out.write("                                         onclick=\"loadmainimg(3);\" class=\"border border-1 thumb-imgs\"/>\r\n");
      out.write("                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages.path_04}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" id=\"pimg4\"\r\n");
      out.write("                                         onclick=\"loadmainimg(4);\" class=\"border border-1 thumb-imgs\"/>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-lg-4 bg-white\">\r\n");
      out.write("                            <h2 class=\"mt-3 mt-lg-0\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("                            <dl>\r\n");
      out.write("                                    ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products.description}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                            </dl>\r\n");
      out.write("                            <hr>\r\n");
      out.write("                            <h6 class=\"text-black-50\">Shipping : LKR.");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products.delivery_fee.intValue()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".00</h6>\r\n");
      out.write("                            <table>\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <td style=\"width: 60%;\">\r\n");
      out.write("                                        <dl>\r\n");
      out.write("                                            <dd class=\"fw-bold\">Brand : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products.modelHasBrand.brand.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</dd>\r\n");
      out.write("                                            <dd class=\"fw-bold\">Model : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products.modelHasBrand.model.name}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</dd>\r\n");
      out.write("                                        </dl>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("                            </table>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row mt-4 p-1 bg-light\">\r\n");
      out.write("                                <div class=\"col-12 p-1\">\r\n");
      out.write("                                    <h4>Seller information</h4>\r\n");
      out.write("                                    <span class=\"d-block text-primary\">100% positive feedbacks</span>\r\n");
      out.write("                                    <span class=\"d-block sm-text\">see feedbacks</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <dl class=\"mt-5\">\r\n");
      out.write("                                <dt><i>Payment methord</i></dt>\r\n");
      out.write("                                <dd class=\"ms-4\">- Cash on delivery</dd>\r\n");
      out.write("                                <dd class=\"ms-4\"><i class=\"bi bi-credit-card-2-front-fill fs-4\"></i> <i\r\n");
      out.write("                                        class=\"bi bi-paypal ms-2\"></i></dd>\r\n");
      out.write("                            </dl>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-lg-3\">\r\n");
      out.write("                            <div class=\"row d-none d-lg-block price-summery-area-spv\">\r\n");
      out.write("                                <div class=\"col-12\">\r\n");
      out.write("                                    <span class=\"fw-bold d-block fs-4\">LKR.");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products.price.intValue()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".00</span>\r\n");
      out.write("                                    <span class=\"text-black-50 d-block\"\r\n");
      out.write("                                          style=\"text-decoration-line: line-through;\">LKR.");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products.price.intValue()+1000}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".00</span>\r\n");
      out.write("\r\n");
      out.write("                                    <!-- Change the `data-field` of buttons and `name` of input field's for multiple plus minus buttons-->\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"quantity buttons_added\">\r\n");
      out.write("                                        <table class=\"mt-3\">\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <h5 class=\"text-dark\">Qty :</h5>\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                                <td>\r\n");
      out.write("                                                    <input type=\"button\" value=\"-\" class=\"ms-2 minus\">\r\n");
      out.write("                                                    <input type=\"number\" step=\"1\" min=\"1\" max=\"\" name=\"quantity\"\r\n");
      out.write("                                                           value=\"1\" title=\"Qty\" class=\"input-text qty text\" size=\"4\"\r\n");
      out.write("                                                           pattern=\"\" inputmode=\"\">\r\n");
      out.write("                                                    <input type=\"button\" value=\"+\" class=\"plus\">\r\n");
      out.write("                                                </td>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </table>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                                        <div class=\"d-flex flex-column mt-4\">\r\n");
      out.write("\r\n");
      out.write("                                            <button onclick=\"addToCart(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\" class=\"details-btn p-2\"\r\n");
      out.write("                                                    type=\"button\">Add to Cart\r\n");
      out.write("                                            </button>\r\n");
      out.write("\r\n");
      out.write("                                            <button onclick=\"addToWishlist(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\"\r\n");
      out.write("                                                    class=\"add-to-wishlist-btn mt-2 p-2\" type=\"button\">Add to Wishlist\r\n");
      out.write("                                            </button>\r\n");
      out.write("\r\n");
      out.write("                                            <button class=\"details-btn p-2 mt-2 bg-drk\"\r\n");
      out.write("                                                    type=\"button\">Buy Now\r\n");
      out.write("                                            </button>\r\n");
      out.write("\r\n");
      out.write("                                        </div>\r\n");
      out.write("\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"row mt-4 p-1 bg-light\">\r\n");
      out.write("                                <div class=\"col-12 p-1\">\r\n");
      out.write("                                    <span class=\"d-block fw-bold\"><i\r\n");
      out.write("                                            class=\"bi bi-bag-check\"></i> Shop with confidence</span>\r\n");
      out.write("                                    <span class=\"sm-text\"><i class=\"bi bi-star-fill\"></i> top rated plus</span>\r\n");
      out.write("                                    <hr>\r\n");
      out.write("                                    <span class=\"d-block mt-1 text-black-50\"><i class=\"bi bi-tag\"></i> trusted seller, fast shipping and easy returns</span>\r\n");
      out.write("                                    <span class=\"d-block mt-1 text-black-50\"><i class=\"bi bi-tag\"></i> radiance  money payback guarantee</span>\r\n");
      out.write("                                    <span class=\"d-block mt-1 text-black-50\"><i class=\"bi bi-tag\"></i> get the item you ordered or get your money back</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- ONLY SMALL DEVICE -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 mt-5 fixed-bottom d-lg-none bg-white\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"row shadow p-1 sm-dvc-spv-summery-area\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-8 mt-1\">\r\n");
      out.write("                            <span class=\"fw-bold d-block fs-4\">LKR.");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products.price.intValue()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".00</span>\r\n");
      out.write("                            <span class=\"text-black-50 d-block\"\r\n");
      out.write("                                  style=\"text-decoration-line: line-through;\">LKR.");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${products.price.intValue()+1000}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".00</span>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"quantity buttons_added\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"row\">\r\n");
      out.write("                                    <div class=\"col-12\">\r\n");
      out.write("                                        <h5 class=\"text-dark\">Qty :</h5>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                    <div class=\"col-12\">\r\n");
      out.write("                                        <input type=\"button\" value=\"-\" class=\"ms-2 minus\">\r\n");
      out.write("                                        <input type=\"number\" step=\"1\" min=\"1\" max=\"\" name=\"quantity\" value=\"1\"\r\n");
      out.write("                                               title=\"Qty\" class=\"input-text qty text bg-white\" size=\"4\" pattern=\"\"\r\n");
      out.write("                                               inputmode=\"\">\r\n");
      out.write("                                        <input type=\"button\" value=\"+\" class=\"plus\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-4 d-grid p-1 price-summery-area-spv\">\r\n");
      out.write("                            <button class=\"spv-add-cart py-2\">Add to Cart</button>\r\n");
      out.write("                            <button class=\"spv-wishlist py-2 mt-1\">Add to Wishlist</button>\r\n");
      out.write("                            <button class=\"buy-now-btn py-2 mt-1\">Buy Now</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- ONLY SMALL DEVICE -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-2 col-lg-4 mt-4 d-flex justify-content-end pe-4\">\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-8 col-lg-4 text-center mt-5\">\r\n");
      out.write("                            <span class=\"main-heading\">Related<span class=\"main-heading clr\"> Items</span></span>\r\n");
      out.write("                            <div class=\"underline-mn\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-2 col-lg-4 mt-5 d-flex justify-content-end pe-4\">\r\n");
      out.write("                            <button class=\"more-btn\">More <i class=\"bi bi-chevron-right ms-2 rght-arw\"></i></button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1 mt-3\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 main-background mt-3 mb-3\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-lg-10 offset-lg-1 pt-3 bg-white rounded-3\">\r\n");
      out.write("\r\n");
      out.write("                            <nav>\r\n");
      out.write("                                <div class=\"nav nav-tabs\" id=\"nav-tab\" role=\"tablist\">\r\n");
      out.write("                                    <button class=\"nav-link active\" id=\"nav-home-tab\" data-bs-toggle=\"tab\"\r\n");
      out.write("                                            data-bs-target=\"#nav-home\" type=\"button\" role=\"tab\" aria-controls=\"nav-home\"\r\n");
      out.write("                                            aria-selected=\"true\">Description\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                    <button class=\"nav-link\" id=\"nav-profile-tab\" data-bs-toggle=\"tab\"\r\n");
      out.write("                                            data-bs-target=\"#nav-profile\" type=\"button\" role=\"tab\"\r\n");
      out.write("                                            aria-controls=\"nav-profile\" aria-selected=\"false\">More\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </nav>\r\n");
      out.write("                            <div class=\"tab-content\" id=\"nav-tabContent\">\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"tab-pane fade show active\" id=\"nav-home\" role=\"tabpanel\"\r\n");
      out.write("                                     aria-labelledby=\"nav-home-tab\">\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row p-2\">\r\n");
      out.write("                                        <div class=\"col-12 mt-2 text-black-50\">\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Color</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>Slate Grey</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Operating System</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>Windows 10 Home</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Processor</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>AMD Ryzen 3 3250U Mobile Processor (2C/4T, 5MB Cache, 3.5 GHz Max\r\n");
      out.write("                                                    Boost)\r\n");
      out.write("                                                </l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Graphics</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>AMD Radeon Graphics</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Display</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>15.6-inch, FHD (1920 x 1080)</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Memory</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>4GB DDR4 on board</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Storage</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>1TB SATA 5400RPM 2.5\" HDD</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">I/O Ports</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>1x USB 3.2 Gen 1 Type-A</l1>\r\n");
      out.write("                                                <l1>1x USB 3.2 Gen 1 Type-C</l1>\r\n");
      out.write("                                                <l1>2x USB 2.0 Type-A</l1>\r\n");
      out.write("                                                <l1>1x HDMI 1.4</l1>\r\n");
      out.write("                                                <l1>1x 3.5mm Combo Audio Jack</l1>\r\n");
      out.write("                                                <l1>Micro SD card reader (on selected model)</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Expansion Slots (includes used)</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>1x DDR4 SO-DIMM slot</l1>\r\n");
      out.write("                                                <l1>1x M.2 2280 PCIe 3.0x2</l1>\r\n");
      out.write("                                                <l1>1x STD 2.5 SATA HDD</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Keyboard & Touchpad</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>Chiclet Keyboard with Num-key</l1>\r\n");
      out.write("                                                <l1>Backlit Chiclet Keyboard</l1>\r\n");
      out.write("                                                <l1>1.4mm Key-travel</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Camera</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>VGA camera</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Audio</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>SonicMaster</l1>\r\n");
      out.write("                                                <l1>Built-in microphone</l1>\r\n");
      out.write("                                                <l1>with Cortana support</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Network and Communication</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>Wi-Fi 5(802.11ac)+Bluetooth 4.1 (Dual band) 1*1</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Battery</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>37WHrs, 2S1P, 2-cell Li-ion</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Power Supply</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>Ã¸4.0, 45W AC Adapter, Output: 19V DC, 2.37A, 45W, Input: 100~240V AC\r\n");
      out.write("                                                    50/60Hz universal\r\n");
      out.write("                                                </l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Weight</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>1.80 kg (3.97 lbs)</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("\r\n");
      out.write("                                            <h4 class=\"fw-bold\">Included in the Box</h4>\r\n");
      out.write("                                            <ul>\r\n");
      out.write("                                                <l1>Mouse</l1>\r\n");
      out.write("                                                <l1>Backpack</l1>\r\n");
      out.write("                                            </ul>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"tab-pane fade\" id=\"nav-profile\" role=\"tabpanel\"\r\n");
      out.write("                                     aria-labelledby=\"nav-profile-tab\">\r\n");
      out.write("\r\n");
      out.write("                                    <div class=\"row\">\r\n");
      out.write("                                        <div class=\"col-12 mt-3\">\r\n");
      out.write("                                            <div class=\"row\">\r\n");
      out.write("                                                <div class=\"col-12 text-center\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages.path_01}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"90%\"\r\n");
      out.write("                                                         height=\"auto\"/>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-12 text-center mt-2\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages.path_02}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"90%\"\r\n");
      out.write("                                                         height=\"auto\"/>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"col-12 text-center mt-2\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages.path_03}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"90%\"\r\n");
      out.write("                                                         height=\"auto\"/>\r\n");
      out.write("                                                </div>\r\n");
      out.write("\r\n");
      out.write("                                                <div class=\"col-12 text-center mt-2\">\r\n");
      out.write("                                                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${productImages.path_04}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"90%\"\r\n");
      out.write("                                                         height=\"auto\"/>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        </body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws jakarta.servlet.jsp.JspException
    {
      jakarta.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(jakarta.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(jakarta.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof jakarta.servlet.jsp.SkipPageException)
            throw (jakarta.servlet.jsp.SkipPageException) e;
        throw new jakarta.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
