/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.7
 * Generated at: 2025-01-05 11:46:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.layout;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.apx.radiance.service.UserService;
import com.apx.radiance.util.JwtTokenUtil;
import com.apx.radiance.entity.User;
import org.hibernate.SessionFactory;
import com.apx.radiance.util.HibernateUtil;
import org.hibernate.Session;
import com.apx.radiance.entity.Cart;
import org.hibernate.query.Query;
import java.util.List;
import com.apx.radiance.entity.Wishlist;
import java.util.Iterator;
import static org.apache.coyote.http11.Constants.a;
import com.apx.radiance.entity.UserType;

public final class base_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/Vidhura/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar!/META-INF/jsp-inheritance.tld", Long.valueOf(1692219220000L));
    _jspx_dependants.put("file:/C:/Users/Vidhura/.m2/repository/lk/callidora/jsp/jsp-template-inheritance/1.0.1/jsp-template-inheritance-1.0.1.jar", Long.valueOf(1692219573000L));
    _jspx_dependants.put("jar:file:/C:/Users/Vidhura/.m2/repository/org/mortbay/jasper/taglibs-standard/10.0.0-M10/taglibs-standard-10.0.0-M10.jar!/META-INF/c.tld", Long.valueOf(1425958870000L));
    _jspx_dependants.put("file:/C:/Users/Vidhura/.m2/repository/org/mortbay/jasper/taglibs-standard/10.0.0-M10/taglibs-standard-10.0.0-M10.jar", Long.valueOf(1606154388000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.apx.radiance.service.UserService");
    _jspx_imports_classes.add("java.util.Iterator");
    _jspx_imports_classes.add("org.hibernate.SessionFactory");
    _jspx_imports_classes.add("org.hibernate.Session");
    _jspx_imports_classes.add("com.apx.radiance.entity.Cart");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.apx.radiance.util.HibernateUtil");
    _jspx_imports_classes.add("org.hibernate.query.Query");
    _jspx_imports_classes.add("com.apx.radiance.entity.User");
    _jspx_imports_classes.add("com.apx.radiance.entity.Wishlist");
    _jspx_imports_classes.add("static org.apache.coyote.http11.Constants.a");
    _jspx_imports_classes.add("com.apx.radiance.util.JwtTokenUtil");
    _jspx_imports_classes.add("com.apx.radiance.entity.UserType");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");


    String userId = "";

    Boolean isSession = false;
    Boolean isAdminSession = false;

    if (session.getAttribute("user") != null) {
        isSession = true;
        userId = session.getAttribute("user").toString();
    } else if (session.getAttribute("admin") != null) {
        isAdminSession = true;
        userId = session.getAttribute("admin").toString();
    }

    List<Wishlist> wishlistList = null;
    List<Cart> cartList = null;
    User user = null;

    if (isSession || isAdminSession) {

        UserService userService = new UserService();
        JwtTokenUtil jwtTokenUtil = new JwtTokenUtil();

        user = userService.getById(Long.valueOf(userId));


        SessionFactory sessionFactory = HibernateUtil.getSessionFactory();
        Session openSession = sessionFactory.openSession();

        Query<Cart> cartQuery = openSession.createQuery("select c from Cart c inner join Product p on c.product.id = p.id where c.user.id=:userID", Cart.class);
        cartList = cartQuery.setParameter("userID", userId).getResultList();

        pageContext.setAttribute("cartItems", cartList);

        Query<Wishlist> wishlistQuery = openSession.createQuery("select w from Wishlist w inner join Product p on w.product.id = p.id where w.user.id=:userID", Wishlist.class);
        wishlistList = wishlistQuery.setParameter("userID", userId).getResultList();

        pageContext.setAttribute("wishListItems", wishlistList);

    }


      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${App.getString('app_name')}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${App.getString('app_description')}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/bootstrap.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/style.css\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/css/summernote.min.css\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/pictures/logos/logo short.svg\" type=\"image/x-icon\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body onscroll=\"scrollEffect();\">\r\n");
      out.write("\r\n");
      out.write("<!-- scroll -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"scroll-top\" id=\"scroll-top\">\r\n");
      out.write("    <svg xmlns=\"http://www.w3.org/2000/svg\" class=\"h-6 w-6\" fill=\"none\" viewBox=\"0 0 24 24\" stroke=\"currentColor\">\r\n");
      out.write("        <path stroke-linecap=\"round\" stroke-linejoin=\"round\" stroke-width=\"2\" d=\"M5 11l7-7 7 7M5 19l7-7 7 7\"/>\r\n");
      out.write("    </svg>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    const scrollTopButton = document.getElementById(\"scroll-top\");\r\n");
      out.write("\r\n");
      out.write("    scrollTopButton.addEventListener('click', () => {\r\n");
      out.write("        window.scrollTo(0, 0);\r\n");
      out.write("    })\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<!-- scroll -->\r\n");
      out.write("\r\n");
      out.write("<div class=\"container-fluid\">\r\n");
      out.write("    <div class=\"row shadow bg-white fixed-top p-1 p-lg-0\" id=\"headerMainShadow\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 d-none d-lg-block\">\r\n");
      out.write("            <div class=\"row text-center top-line-area text-white\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-3 text-end text-white\">\r\n");
      out.write("                    <span class=\"sm-text\"><i class=\"bi bi-envelope-fill em-icn\"></i> Radiance .info@gmail.com</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-6\">\r\n");
      out.write("                    <span class=\"sm-text\">Radiance | The Best Electronic Items at the Right Place</span>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-3 text-start\">\r\n");
      out.write("                    <!-- <button><i class=\"bi bi-instagram social-btn\"></i></button>\r\n");
      out.write("                    <button><i class=\"bi bi-messenger social-btn\"></i></button>\r\n");
      out.write("                    <button><i class=\"bi bi-twitter social-btn\"></i></button>\r\n");
      out.write("                    <button><i class=\"bi bi-linkedin social-btn\"></i></button> -->\r\n");
      out.write("\r\n");
      out.write("                    <table>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                            <td class=\"px-2\"><i class=\"bi bi-instagram social-btn\"></i></td>\r\n");
      out.write("                            <td class=\"px-2\"><i class=\"bi bi-twitter social-btn\"></i></td>\r\n");
      out.write("                            <td class=\"px-2\"><i class=\"bi bi-linkedin social-btn\"></i></td>\r\n");
      out.write("                            <td class=\"px-2\"><i class=\"bi bi-messenger social-btn\"></i></td>\r\n");
      out.write("                            <td class=\"px-2\"><i class=\"bi bi-youtube social-btn\"></i></td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                    </table>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 col-lg-10 offset-lg-1 mt-2\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-10 col-lg-3 text-lg-center\">\r\n");
      out.write("                    <div onclick=\"test();\" class=\"logo\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-2 d-block d-lg-none d-flex justify-content-end\">\r\n");
      out.write("                    <button class=\"menu-btn\" type=\"button\" data-bs-toggle=\"offcanvas\" data-bs-target=\"#offcanvasExample\"\r\n");
      out.write("                            aria-controls=\"offcanvasExample\"><i class=\"bi bi-list fs-3\"></i></button>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <!-- small device -->\r\n");
      out.write("                <div class=\"offcanvas offcanvas-end\" tabindex=\"-1\" id=\"offcanvasExample\"\r\n");
      out.write("                     aria-labelledby=\"offcanvasExampleLabel\">\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"offcanvas-header\">\r\n");
      out.write("                        <h5 class=\"offcanvas-title\" id=\"offcanvasExampleLabel\">Menu</h5>\r\n");
      out.write("                        <button type=\"button\" class=\"btn-close text-reset\" data-bs-dismiss=\"offcanvas\"\r\n");
      out.write("                                aria-label=\"Close\"></button>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"offcanvas-body\">\r\n");
      out.write("                        <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 p-2\">\r\n");
      out.write("                                <span class=\"\">Home</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 p-2\">\r\n");
      out.write("                                <div class=\"dropdown\" onclick=\"go_to_products();\">\r\n");
      out.write("                                    <span type=\"button\" id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                                          aria-expanded=\"false\">All Products</span>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 p-2\">\r\n");
      out.write("                                <span class=\"\">Categories</span>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"py-2\">\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Electronic Devices</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Mobile Accessories</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Computer Accessories</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Camera Accessories</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Computer Components</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Network Components</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">TV and Video Devices</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Cooling and Heating</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Washing Machines</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 p-2\">\r\n");
      out.write("                                <span class=\"\">Brands</span>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"py-2\">\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Apple</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Samsung</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Huawei</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">TLC</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Softlogic</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Sony</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 p-2\">\r\n");
      out.write("                                <span class=\"\">About Us</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 p-2\">\r\n");
      out.write("                                <span class=\"\">Contact Us</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"col-12 p-2\">\r\n");
      out.write("                                <span class=\"\">Account</span>\r\n");
      out.write("\r\n");
      out.write("                                <div class=\"py-2\">\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin-panel\">My Account</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("wishlist\">Wishlist</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("cart\">Cart</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">My Orders</a>\r\n");
      out.write("                                    <a class=\"dropdown-item text-black-50\" href=\"#\">Log Out</a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- small device -->\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-6 pt-3\">\r\n");
      out.write("                    <div class=\"input-group border-my mb-3\">\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Search..\" aria-label=\"Recipient's username\"\r\n");
      out.write("                               aria-describedby=\"basic-addon2\">\r\n");
      out.write("                        <span class=\"input-group-text\" id=\"basic-addon2\"><i class=\"bi bi-search\"></i></span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-1 text-center pt-3 d-none d-lg-block c-pointer text-black-50\" onclick=\"go_to_cart();\">\r\n");
      out.write("                    <i class=\"bi bi-bag fs-5\"></i>\r\n");
      out.write("\r\n");
      out.write("                    ");

                        Double netTotal = 0.0;
                        Double netTotalWishList = 0.0;

                        int cartQty = 0;
                        int wishListQty = 0;

                        String profileNavigation = "Account";

                        if (isSession || isAdminSession) {

                            cartQty = cartList.size();
                            wishListQty = wishlistList.size();

                            profileNavigation = user.getFirst_name();

                            Iterator<Cart> iterator = cartList.iterator();
                            while (iterator.hasNext()) {
                                Cart cartData = iterator.next();
                                netTotal = netTotal + cartData.getProduct().getPrice();
                            }

                            Iterator<Wishlist> iterator2 = wishlistList.iterator();
                            while (iterator2.hasNext()) {
                                Wishlist wishlistData = iterator2.next();
                                netTotalWishList = netTotalWishList + wishlistData.getProduct().getPrice();
                            }

                        }

                    
      out.write("\r\n");
      out.write("                    <span class=\"d-block xsm-text fw-bold\">");
      out.print(netTotal.intValue());
      out.write(".00</span>\r\n");
      out.write("                    <label class=\"num-label\">");
      out.print(cartQty);
      out.write("\r\n");
      out.write("                    </label>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-1 text-center pt-3 d-none d-lg-block c-pointer text-black-50\"\r\n");
      out.write("                     onclick=\"go_to_wishlist();\">\r\n");
      out.write("                    <i class=\"bi bi-heart fs-5\"></i>\r\n");
      out.write("                    <span class=\"d-block xsm-text fw-bold\">");
      out.print(netTotalWishList.intValue());
      out.write(".00</span>\r\n");
      out.write("                    <label class=\"num-label\">");
      out.print(wishListQty);
      out.write("\r\n");
      out.write("                    </label>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-1 text-center pt-3 d-none d-lg-block\">\r\n");
      out.write("                    <i class=\"bi bi-person-circle fs-5\" type=\"button\" id=\"dropdownMenuButton1\" data-bs-toggle=\"dropdown\"\r\n");
      out.write("                       aria-expanded=\"false\"></i>\r\n");
      out.write("                    <span class=\"d-block sm-text fw-bold\" type=\"button\" id=\"dropdownMenuButton1\"\r\n");
      out.write("                          data-bs-toggle=\"dropdown\"\r\n");
      out.write("                          aria-expanded=\"false\">");
      out.print(profileNavigation);
      out.write("</span>\r\n");
      out.write("\r\n");
      out.write("                    <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("\r\n");
      out.write("                        ");

                            if (isSession) {
                        
      out.write("\r\n");
      out.write("                        <li><a class=\"dropdown-item\" onclick=\"test()\">My Account</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("wishlist\">Wishlist</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("cart\">Cart</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("purchased-history\">My Orders</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Sell with Radiance </a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("purchased-history\">Purchased History</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"dropdown-item c-pointer\" onclick=\"logOut();\">Log Out</a></li>\r\n");
      out.write("                        ");

                        } else if (isAdminSession) {
                        
      out.write("\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("admin-panel\">Admin Panel</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" onclick=\"test()\">My Account</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("wishlist\">Wishlist</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("cart\">Cart</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("purchased-history\">My Orders</a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"#\">Sell with Radiance </a></li>\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("purchased-history\">Purchased History</a>\r\n");
      out.write("                        </li>\r\n");
      out.write("                        <li><a class=\"dropdown-item c-pointer\" onclick=\"logOut();\">Log Out</a></li>\r\n");
      out.write("                        ");

                        } else {
                        
      out.write("\r\n");
      out.write("                        <li><a class=\"dropdown-item\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("sign-in\">Sign In</a></li>\r\n");
      out.write("                        ");

                            }

                        
      out.write("\r\n");
      out.write("\r\n");
      out.write("                    </ul>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 d-none d-lg-block\">\r\n");
      out.write("            <div class=\"row text-center\">\r\n");
      out.write("                <div class=\"col-12 col-lg-10 offset-lg-1\">\r\n");
      out.write("                    <div class=\"row pb-3 pt-1\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-2 c-pointer\">\r\n");
      out.write("                            <span class=\"text-black-50\" onclick=\"go_to_home();\">Home</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-2\">\r\n");
      out.write("                            <div class=\"dropdown\" onclick=\"go_to_products();\">\r\n");
      out.write("                                <span class=\"text-black-50\" type=\"button\" id=\"dropdownMenuButton1\"\r\n");
      out.write("                                      data-bs-toggle=\"dropdown\" aria-expanded=\"false\">All Products</span>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-2\">\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"dropdown\">\r\n");
      out.write("                                <span class=\"text-black-50\" type=\"button\" id=\"dropdownMenuButton1\"\r\n");
      out.write("                                      data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Categories <i\r\n");
      out.write("                                        class=\"bi bi-arrow-down-short dp-icons\"></i></span>\r\n");
      out.write("\r\n");
      out.write("                                <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">Electronic Devices</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">Mobile Accessories</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">Computer Accessories</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">Camera Accessories</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">Computer Components</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">Network Components</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">TV and Video Devices</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">Cooling and Heating</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">Washing Machines</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-2\">\r\n");
      out.write("                            <div class=\"dropdown\">\r\n");
      out.write("                                <span class=\"text-black-50\" type=\"button\" id=\"dropdownMenuButton1\"\r\n");
      out.write("                                      data-bs-toggle=\"dropdown\" aria-expanded=\"false\">Brands <i\r\n");
      out.write("                                        class=\"bi bi-arrow-down-short dp-icons\"></i></span>\r\n");
      out.write("\r\n");
      out.write("                                <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuButton1\">\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">Apple</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">Samsung</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">Huawei</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">TLC</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">Softlogic</a></li>\r\n");
      out.write("                                    <li><a class=\"dropdown-item\" href=\"#\">Sony</a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-2\">\r\n");
      out.write("                            <span class=\"text-black-50\">About Us</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-2\">\r\n");
      out.write("                            <span class=\"text-black-50\">Contact Us</span>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"empty-area\"></div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      if (_jspx_meth_layout_005fblock_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <div class=\"row bg-dark text-center text-md-start\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-12 col-lg-10 offset-lg-1 text-white p-5\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-3\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12 d-flex justify-content-center justify-content-lg-start\">\r\n");
      out.write("                            <div class=\"logo-white\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12 mt-2\">\r\n");
      out.write("                            <p class=\"text-white-50\">Radiance Electronics.The best electonic items at the right\r\n");
      out.write("                                place.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-3\">\r\n");
      out.write("                    <span class=\"d-block footer-titles\">My Account</span>\r\n");
      out.write("                    <a href=\"\" class=\"d-block footer-links\">My Account</a>\r\n");
      out.write("                    <a href=\"\" class=\"d-block footer-links\">Checkout</a>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("cart\" class=\"d-block footer-links\">Shopping Cart</a>\r\n");
      out.write("                    <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("wishlist\" class=\"d-block footer-links\">Wishlist</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-3\">\r\n");
      out.write("                    <span class=\"d-block footer-titles\">Custommer Care</span>\r\n");
      out.write("                    <a href=\"\" class=\"d-block footer-links\">Help Center</a>\r\n");
      out.write("                    <a href=\"\" class=\"d-block footer-links\">How to Buy</a>\r\n");
      out.write("                    <a href=\"\" class=\"d-block footer-links\">Track Your Order</a>\r\n");
      out.write("                    <a href=\"\" class=\"d-block footer-links\">Returns & Refunds</a>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"col-12 col-lg-3\">\r\n");
      out.write("                    <span class=\"d-block footer-titles\">Faq</span>\r\n");
      out.write("                    <a href=\"\" class=\"d-block footer-links\">Faq</a>\r\n");
      out.write("                    <a href=\"\" class=\"d-block footer-links\">Contact Us</a>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"mt-2\">\r\n");
      out.write("\r\n");
      out.write("                        <button class=\"social-btns\"><i class=\"bi bi-facebook\"></i></button>\r\n");
      out.write("                        <button class=\"social-btns\"><i class=\"bi bi-instagram\"></i></button>\r\n");
      out.write("                        <button class=\"social-btns\"><i class=\"bi bi-twitter\"></i></button>\r\n");
      out.write("                        <button class=\"social-btns\"><i class=\"bi bi-linkedin\"></i></button>\r\n");
      out.write("                        <button class=\"social-btns\"><i class=\"bi bi-youtube\"></i></button>\r\n");
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"mt-2\">\r\n");
      out.write("                        <div class=\"input-group mb-3\">\r\n");
      out.write("                            <input type=\"text\" class=\"form-control bg-drk\" aria-describedby=\"button-addon2\">\r\n");
      out.write("                            <button class=\"send-btn p-2\" type=\"button\" id=\"button-addon2\">Send</button>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <hr>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-12 text-center\">\r\n");
      out.write("                    <span class=\"sm-text text-white-50\">&copy; Radiance . All right Reserved.</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    const BASE_URL = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/bootstrap.bundle.js\"></script>\r\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/script.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/summernote.min.js\"></script>\r\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${BASE_URL}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("assets/js/spartan-multi-image-picker.js\"></script>\r\n");
      out.write("<script src=\"//code.tidio.co/obgngwi69oy3kootdyykcvyeujlvlgs1.js\" async></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_layout_005fblock_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    //  layout:block
    lk.callidora.jsp.inheritance.BlockTag _jspx_th_layout_005fblock_005f0 = new lk.callidora.jsp.inheritance.BlockTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_layout_005fblock_005f0);
    try {
      _jspx_th_layout_005fblock_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/layout/base.jsp(403,4) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_layout_005fblock_005f0.setName("contents");
      _jspx_th_layout_005fblock_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_layout_005fblock_005f0);
    }
    return false;
  }
}
